//TODO: Fix null particle crash (for e.g Stupefy) (seems unfixable!)

package snidgert.harrypottermod;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.entity.RenderItem;
import net.minecraft.client.resources.model.ModelResourceLocation;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemStack;
import net.minecraft.potion.Potion;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.common.registry.EntityRegistry;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import snidgert.harrypottermod.armor.AurorArmorClass;
import snidgert.harrypottermod.armor.DeathEaterArmorClass;
import snidgert.harrypottermod.armor.InvisibilityCloakArmorClass;
import snidgert.harrypottermod.armor.WerewolfArmorClass;
import snidgert.harrypottermod.blocks.AcromantulaWebClass;
import snidgert.harrypottermod.blocks.BlackMarbleBrickClass;
import snidgert.harrypottermod.blocks.BlackMarbleClass;
import snidgert.harrypottermod.blocks.BoggartChestLockedClass;
import snidgert.harrypottermod.blocks.BoggartChestOpenClass;
import snidgert.harrypottermod.blocks.BrickClass;
import snidgert.harrypottermod.blocks.BrokenGlassClass;
import snidgert.harrypottermod.blocks.CabinetClass;
import snidgert.harrypottermod.blocks.CrystalballClass;
import snidgert.harrypottermod.blocks.CupClass;
import snidgert.harrypottermod.blocks.DarkMarkClass;
import snidgert.harrypottermod.blocks.DiademClass;
import snidgert.harrypottermod.blocks.DiaryClass;
import snidgert.harrypottermod.blocks.GOFClass;
import snidgert.harrypottermod.blocks.GlowstoneOffClass;
import snidgert.harrypottermod.blocks.GoldenEggClass;
import snidgert.harrypottermod.blocks.GoldenEggOpenClass;
import snidgert.harrypottermod.blocks.HandClass;
import snidgert.harrypottermod.blocks.HatClass;
import snidgert.harrypottermod.blocks.LampOffClass;
import snidgert.harrypottermod.blocks.LocketClass;
import snidgert.harrypottermod.blocks.MagicCauldronClass;
import snidgert.harrypottermod.blocks.MagicPowerOreClass;
import snidgert.harrypottermod.blocks.MarbleClass;
import snidgert.harrypottermod.blocks.MarblePillarClass;
import snidgert.harrypottermod.blocks.MirrorClass;
import snidgert.harrypottermod.blocks.PensieveClass;
import snidgert.harrypottermod.blocks.PensievePlaneClass;
import snidgert.harrypottermod.blocks.RingClass;
import snidgert.harrypottermod.blocks.RubyOreClass;
import snidgert.harrypottermod.blocks.SilverOreClass;
import snidgert.harrypottermod.blocks.SmoothBlackMarbleClass;
import snidgert.harrypottermod.blocks.SmoothMarbleClass;
import snidgert.harrypottermod.blocks.StoneSoldierBlockClass;
import snidgert.harrypottermod.blocks.StunClass;
import snidgert.harrypottermod.blocks.TorchOffClass;
import snidgert.harrypottermod.blocks.TriCupClass;
import snidgert.harrypottermod.blocks.WandCrafterClass;
import snidgert.harrypottermod.blocks.WingardiumLeviosaBlockClass;
import snidgert.harrypottermod.creativetabs.MagicFoodClass;
import snidgert.harrypottermod.creativetabs.MagicItemsClass;
import snidgert.harrypottermod.creativetabs.MagicMaterialsClass;
import snidgert.harrypottermod.creativetabs.SpellTabClass;
import snidgert.harrypottermod.creativetabs.WandCraftingClass;
import snidgert.harrypottermod.food.Bean10Class;
import snidgert.harrypottermod.food.Bean1Class;
import snidgert.harrypottermod.food.Bean2Class;
import snidgert.harrypottermod.food.Bean3Class;
import snidgert.harrypottermod.food.Bean4Class;
import snidgert.harrypottermod.food.Bean5Class;
import snidgert.harrypottermod.food.Bean6Class;
import snidgert.harrypottermod.food.Bean7Class;
import snidgert.harrypottermod.food.Bean8Class;
import snidgert.harrypottermod.food.Bean9Class;
import snidgert.harrypottermod.food.ButterBeerClass;
import snidgert.harrypottermod.food.ChocolateFrogClass;
import snidgert.harrypottermod.food.EveryFlavourBeansClass;
import snidgert.harrypottermod.food.GillyweedClass;
import snidgert.harrypottermod.food.NogtailCookedClass;
import snidgert.harrypottermod.food.NogtailRawClass;
import snidgert.harrypottermod.food.RamoraCookedClass;
import snidgert.harrypottermod.food.RamoraRawClass;
import snidgert.harrypottermod.food.TeboCookedClass;
import snidgert.harrypottermod.food.TeboRawClass;
import snidgert.harrypottermod.food.TileEntityEveryFlavourBeans;
import snidgert.harrypottermod.generation.WizardWorldGen;
import snidgert.harrypottermod.gui.GuiHandler;
import snidgert.harrypottermod.gui.SpellGUI;
import snidgert.harrypottermod.items.AugureyFeatherClass;
import snidgert.harrypottermod.items.BFangClass;
import snidgert.harrypottermod.items.BasiliskScaleClass;
import snidgert.harrypottermod.items.BatClass;
import snidgert.harrypottermod.items.BillywigStingerClass;
import snidgert.harrypottermod.items.BirchStickClass;
import snidgert.harrypottermod.items.BludgerClass;
import snidgert.harrypottermod.items.BoomslangVenomClass;
import snidgert.harrypottermod.items.BroomstickClass;
import snidgert.harrypottermod.items.ChimaeraScaleFragmentClass;
import snidgert.harrypottermod.items.DeluminatorClass;
import snidgert.harrypottermod.items.DemiguiseHairClass;
import snidgert.harrypottermod.items.DoxyWingClass;
import snidgert.harrypottermod.items.DragonHeartStringClass;
import snidgert.harrypottermod.items.ErumpentHideClass;
import snidgert.harrypottermod.items.FairyWingClass;
import snidgert.harrypottermod.items.FordAngliaClass;
import snidgert.harrypottermod.items.FwooperFeatherClass;
import snidgert.harrypottermod.items.GalleonClass;
import snidgert.harrypottermod.items.HippogriffFeatherClass;
import snidgert.harrypottermod.items.ItemStoreClass;
import snidgert.harrypottermod.items.KelpieHairClass;
import snidgert.harrypottermod.items.KeyClass;
import snidgert.harrypottermod.items.KnutClass;
import snidgert.harrypottermod.items.MagicBookClass;
import snidgert.harrypottermod.items.MagicPowderClass;
import snidgert.harrypottermod.items.MaraudersMapClass;
import snidgert.harrypottermod.items.MasterKeyClass;
import snidgert.harrypottermod.items.MirrorShardClass;
import snidgert.harrypottermod.items.MonsterBookClass;
import snidgert.harrypottermod.items.Motercycle2Class;
import snidgert.harrypottermod.items.MotercycleClass;
import snidgert.harrypottermod.items.OakStickClass;
import snidgert.harrypottermod.items.PStoneClass;
import snidgert.harrypottermod.items.PenknifeClass;
import snidgert.harrypottermod.items.PhoenixFeatherClass;
import snidgert.harrypottermod.items.PutOuterClass;
import snidgert.harrypottermod.items.QuaffleClass;
import snidgert.harrypottermod.items.RStoneClass;
import snidgert.harrypottermod.items.RemembrallClass;
import snidgert.harrypottermod.items.RowanStickClass;
import snidgert.harrypottermod.items.RubyClass;
import snidgert.harrypottermod.items.SickleClass;
import snidgert.harrypottermod.items.SilverIngotClass;
import snidgert.harrypottermod.items.SockClass;
import snidgert.harrypottermod.items.TheGoldenSnitchClass;
import snidgert.harrypottermod.items.TimeTurnerClass;
import snidgert.harrypottermod.items.TridentClass;
import snidgert.harrypottermod.items.UnicornHairClass;
import snidgert.harrypottermod.items.VeelaHairClass;
import snidgert.harrypottermod.items.WerewolfFormClass;
import snidgert.harrypottermod.magiceffects.ShieldEffectClass;
import snidgert.harrypottermod.mobs.entity.EntityAragog;
import snidgert.harrypottermod.mobs.entity.EntityAugurey;
import snidgert.harrypottermod.mobs.entity.EntityBasilisk;
import snidgert.harrypottermod.mobs.entity.EntityBillywig;
import snidgert.harrypottermod.mobs.entity.EntityBird;
import snidgert.harrypottermod.mobs.entity.EntityBludger;
import snidgert.harrypottermod.mobs.entity.EntityBoggartDementor;
import snidgert.harrypottermod.mobs.entity.EntityBook;
import snidgert.harrypottermod.mobs.entity.EntityBowtruckle;
import snidgert.harrypottermod.mobs.entity.EntityBundimun;
import snidgert.harrypottermod.mobs.entity.EntityCabinet;
import snidgert.harrypottermod.mobs.entity.EntityCabinet2;
import snidgert.harrypottermod.mobs.entity.EntityCatForm;
import snidgert.harrypottermod.mobs.entity.EntityCentaur;
import snidgert.harrypottermod.mobs.entity.EntityChizpurfle;
import snidgert.harrypottermod.mobs.entity.EntityClabbert;
import snidgert.harrypottermod.mobs.entity.EntityDementor;
import snidgert.harrypottermod.mobs.entity.EntityDemiguise;
import snidgert.harrypottermod.mobs.entity.EntityDogForm;
import snidgert.harrypottermod.mobs.entity.EntityDugbog;
import snidgert.harrypottermod.mobs.entity.EntityFairy;
import snidgert.harrypottermod.mobs.entity.EntityFalconForm;
import snidgert.harrypottermod.mobs.entity.EntityFiendfyreDragon;
import snidgert.harrypottermod.mobs.entity.EntityFireCrab;
import snidgert.harrypottermod.mobs.entity.EntityFlobberworm;
import snidgert.harrypottermod.mobs.entity.EntityFluffy;
import snidgert.harrypottermod.mobs.entity.EntityFlyingBroomstick;
import snidgert.harrypottermod.mobs.entity.EntityFordAnglia;
import snidgert.harrypottermod.mobs.entity.EntityFwooper;
import snidgert.harrypottermod.mobs.entity.EntityGhost;
import snidgert.harrypottermod.mobs.entity.EntityGhoul;
import snidgert.harrypottermod.mobs.entity.EntityGnome;
import snidgert.harrypottermod.mobs.entity.EntityGoblin;
import snidgert.harrypottermod.mobs.entity.EntityGoldenSnitch;
import snidgert.harrypottermod.mobs.entity.EntityGraphorn;
import snidgert.harrypottermod.mobs.entity.EntityGriffin;
import snidgert.harrypottermod.mobs.entity.EntityGrindylow;
import snidgert.harrypottermod.mobs.entity.EntityHippocampus;
import snidgert.harrypottermod.mobs.entity.EntityHippogriff;
import snidgert.harrypottermod.mobs.entity.EntityHorklump;
import snidgert.harrypottermod.mobs.entity.EntityHorntail;
import snidgert.harrypottermod.mobs.entity.EntityHouseElf;
import snidgert.harrypottermod.mobs.entity.EntityImp;
import snidgert.harrypottermod.mobs.entity.EntityImperioMob;
import snidgert.harrypottermod.mobs.entity.EntityJarvey;
import snidgert.harrypottermod.mobs.entity.EntityJobberknoll;
import snidgert.harrypottermod.mobs.entity.EntityKelpie;
import snidgert.harrypottermod.mobs.entity.EntityKey;
import snidgert.harrypottermod.mobs.entity.EntityKnarl;
import snidgert.harrypottermod.mobs.entity.EntityKneazle;
import snidgert.harrypottermod.mobs.entity.EntityLeprechaun;
import snidgert.harrypottermod.mobs.entity.EntityLevitate;
import snidgert.harrypottermod.mobs.entity.EntityMasterKey;
import snidgert.harrypottermod.mobs.entity.EntityMermaid;
import snidgert.harrypottermod.mobs.entity.EntityMoke;
import snidgert.harrypottermod.mobs.entity.EntityMonsterBook;
import snidgert.harrypottermod.mobs.entity.EntityMotorbike;
import snidgert.harrypottermod.mobs.entity.EntityMotorbike2;
import snidgert.harrypottermod.mobs.entity.EntityNagini;
import snidgert.harrypottermod.mobs.entity.EntityNogtail;
import snidgert.harrypottermod.mobs.entity.EntityNundu;
import snidgert.harrypottermod.mobs.entity.EntityOccamy;
import snidgert.harrypottermod.mobs.entity.EntityOwlForm;
import snidgert.harrypottermod.mobs.entity.EntityPatronus;
import snidgert.harrypottermod.mobs.entity.EntityPhoenix;
import snidgert.harrypottermod.mobs.entity.EntityPhoenixForm;
import snidgert.harrypottermod.mobs.entity.EntityPixie;
import snidgert.harrypottermod.mobs.entity.EntityPuffskein;
import snidgert.harrypottermod.mobs.entity.EntityQuaffle;
import snidgert.harrypottermod.mobs.entity.EntityQuintaped;
import snidgert.harrypottermod.mobs.entity.EntityRamora;
import snidgert.harrypottermod.mobs.entity.EntityRatForm;
import snidgert.harrypottermod.mobs.entity.EntityRavenForm;
import snidgert.harrypottermod.mobs.entity.EntityRedCap;
import snidgert.harrypottermod.mobs.entity.EntityReem;
import snidgert.harrypottermod.mobs.entity.EntityRunespoor;
import snidgert.harrypottermod.mobs.entity.EntityShield;
import snidgert.harrypottermod.mobs.entity.EntitySnake;
import snidgert.harrypottermod.mobs.entity.EntitySnidget;
import snidgert.harrypottermod.mobs.entity.EntitySnidgetForm;
import snidgert.harrypottermod.mobs.entity.EntityStagForm;
import snidgert.harrypottermod.mobs.entity.EntityStoneSoldier;
import snidgert.harrypottermod.mobs.entity.EntityTebo;
import snidgert.harrypottermod.mobs.entity.EntityThestral;
import snidgert.harrypottermod.mobs.entity.EntityTroll;
import snidgert.harrypottermod.mobs.entity.EntityUkaranianIronbelly;
import snidgert.harrypottermod.mobs.entity.EntityUnicorn;
import snidgert.harrypottermod.mobs.entity.EntityVeela;
import snidgert.harrypottermod.mobs.entity.EntityWerewolf;
import snidgert.harrypottermod.mobs.entity.EntityWerewolfMob;
import snidgert.harrypottermod.mobs.entity.EntityWingedHorse;
import snidgert.harrypottermod.projectiles.AraniaExumaiProjectile;
import snidgert.harrypottermod.projectiles.AvadakedavraProjectile;
import snidgert.harrypottermod.projectiles.ConfringoProjectile;
import snidgert.harrypottermod.projectiles.ConfringoStrongProjectile;
import snidgert.harrypottermod.projectiles.ConfundoProjectile;
import snidgert.harrypottermod.projectiles.ConfundoStrongProjectile;
import snidgert.harrypottermod.projectiles.CrucioProjectile;
import snidgert.harrypottermod.projectiles.CrucioStrongProjectile;
import snidgert.harrypottermod.projectiles.ExpelliarmusProjectile;
import snidgert.harrypottermod.projectiles.ExpelliarmusStrongProjectile;
import snidgert.harrypottermod.projectiles.ImperioProjectile;
import snidgert.harrypottermod.projectiles.IncendioProjectile;
import snidgert.harrypottermod.projectiles.LevicorpusProjectile;
import snidgert.harrypottermod.projectiles.LevicorpusStrongProjectile;
import snidgert.harrypottermod.projectiles.PatronusProjectile;
import snidgert.harrypottermod.projectiles.PatronusStrongProjectile;
import snidgert.harrypottermod.projectiles.ReductoProjectile;
import snidgert.harrypottermod.projectiles.ReductoStrongProjectile;
import snidgert.harrypottermod.projectiles.SectumsempraProjectile;
import snidgert.harrypottermod.projectiles.SectumsempraStrongProjectile;
import snidgert.harrypottermod.projectiles.StunProjectile;
import snidgert.harrypottermod.projectiles.StunStrongProjectile;
import snidgert.harrypottermod.projectiles.StupefyProjectile;
import snidgert.harrypottermod.projectiles.StupefyStrongProjectile;
import snidgert.harrypottermod.spellsystem.MagicLeveling;
import snidgert.harrypottermod.tileentities.TileEntityBoggartChestLocked;
import snidgert.harrypottermod.tileentities.TileEntityBoggartChestOpen;
import snidgert.harrypottermod.tileentities.TileEntityCabinet;
import snidgert.harrypottermod.tileentities.TileEntityCrystalball;
import snidgert.harrypottermod.tileentities.TileEntityCup;
import snidgert.harrypottermod.tileentities.TileEntityDarkMarkClass;
import snidgert.harrypottermod.tileentities.TileEntityDiadem;
import snidgert.harrypottermod.tileentities.TileEntityDiary;
import snidgert.harrypottermod.tileentities.TileEntityGOF;
import snidgert.harrypottermod.tileentities.TileEntityGoldenEgg;
import snidgert.harrypottermod.tileentities.TileEntityGoldenEggOpen;
import snidgert.harrypottermod.tileentities.TileEntityHand;
import snidgert.harrypottermod.tileentities.TileEntityHat;
import snidgert.harrypottermod.tileentities.TileEntityLocket;
import snidgert.harrypottermod.tileentities.TileEntityMirror;
import snidgert.harrypottermod.tileentities.TileEntityPensieve;
import snidgert.harrypottermod.tileentities.TileEntityPensievePlane;
import snidgert.harrypottermod.tileentities.TileEntityRing;
import snidgert.harrypottermod.tileentities.TileEntityStoneSoldierBlock;
import snidgert.harrypottermod.tileentities.TileEntityTriCup;
import snidgert.harrypottermod.tileentities.TileEntityWandCrafter;
import snidgert.harrypottermod.tools.SwordofGryffindorClass;
import snidgert.harrypottermod.wands.DPSWandClass;
import snidgert.harrypottermod.wands.ElderWandClass;
import snidgert.harrypottermod.wands.SupportWandClass;
import snidgert.harrypottermod.wands.TankWandClass;

@Mod(modid = "harrypottermod", name = "Harry Potter Mod", version = "v2.0")
public class MainClass {

	@SidedProxy(clientSide = "snidgert.harrypottermod.ClientProxy", serverSide = "snidgert.harrypottermod.CommonProxy")
	public static CommonProxy proxy;
	public static int InvisibilityCloakID;
	public static int AurorChestID;
	public static int AurorLegsID;
	public static int AurorHatID;
	public static int AurorShoesID;
	public static int DeathEaterChestID;
	public static int DeathEaterLegsID;
	public static int DeathEaterHatID;
	public static int DeathEaterShoesID;
	public static int WerewolfChestID;
	public static int WerewolfLegsID;
	public static int WerewolfHeadID;
	public static int WerewolfFeetID;
	public static int startEntityId = 300;
	public static final String MODID = "harrypottermod";
	public static final String NAME = "Harry Potter Mod";
	public static final String VERSION = "v2.0";
	@Mod.Instance("harrypottermod")
	public static MainClass instance;
	private static int modGuiIndex = 0;
	public static final int GUI_ITEM_INV = MainClass.modGuiIndex++;;
	public static final int Spell = 2;
	public static final int RemembrallGui = 3;
	public static final int WandCrafterGUI = 4;
	public static CreativeTabs SpellTab;
	public static CreativeTabs MagicFood;
	public static CreativeTabs MagicItems;
	public static CreativeTabs MagicMaterials;
	public static CreativeTabs WandCrafting;
	public static Item.ToolMaterial MagicWeaponMaterial;
	public static ItemArmor.ArmorMaterial MagicArmorMaterial;
	public static Item.ToolMaterial TridentMaterial;
	public static ItemArmor.ArmorMaterial AurorArmor;
	public static ItemArmor.ArmorMaterial DeathEaterArmor;
	public static ItemArmor.ArmorMaterial WerewolfFur;
	public WizardWorldGen eventWorldGen;
	public static Potion ShieldEffect;
	public static Block RubyOre;
	public static Block SilverOre;
	public static Block Brick;
	public static Block Marble;
	public static Block MarblePillar;
	public static Block BlackMarble;
	public static Block SmoothMarble;
	public static Block SmoothBlackMarble;
	public static Block BlackMarbleBrick;
	public static Block DarkMark;
	public static Block BrokenGlass;
	public static Block Stun;
	public static Block Cup;
	public static Block Crystalball;
	public static Block TriCup;
	public static Block WingardiumLeviosaBlock;
	public static Block Diadem;
	public static Block Diary;
	public static Block GoldenEgg;
	public static Block GoldenEggOpen;
	public static Block PensievePlane;
	public static Block Pensieve;
	public static Block Locket;
	public static Block Ring;
	public static Block Hand;
	public static Block Mirror;
	public static Block TorchOff;
	public static Block LampOff;
	public static Block GlowstoneOff;
	public static Block GOF;
	public static Block Cabinet;
	public static Block EveryFlavourBeans;
	public static Block Hat;
	public static Block MagicCauldron;
	public static Block BoggartChestLocked;
	public static Block BoggartChestOpen;
	public static Block WandCrafterIdle;
	public static Block WandCrafterActive;
	public static Block MagicPowerOre;
	public static Block AcromantulaWeb;
	public static Block StoneSoldierBlock;
	public static Item SilverIngot;
	public static Item Ruby;
	public static Item Bat;
	public static Item MagicBook;
	public static Item MonsterBook;
	public static Item TheGoldenSnitch;
	public static Item Quaffle;
	public static Item Bludger;
	public static Item FordAnglia;
	public static Item Motercycle;
	public static Item Motercycle2;
	public static Item Broomstick;
	public static Item MaraudersMap;
	public static Item WerewolfForm;
	public static Item PhoenixFeather;
	public static Item PStone;
	public static Item Deluminator;
	public static Item PutOuter;
	public static Item Penknife;
	public static Item ItemStore;
	public static Item Key;
	public static Item MasterKey;
	public static Item RStone;
	public static Item ElderWand;
	public static Item BFang;
	public static Item MirrorShard;
	public static Item Sock;
	public static Item HippogriffFeather;
	public static Item Remembrall;
	public static Item WoodWand;
	public static Item OakStick;
	public static Item BirchStick;
	public static Item BirchPhoenix;
	public static Item OakPhoenix;
	public static Item MagicPower;
	public static Item BirchHippogriff;
	public static Item OakHippogriff;
	public static Item DragonHeartString;
	public static Item BirchDragon;
	public static Item OakDragon;
	public static Item BasiliskScale;
	public static Item BirchBasilisk;
	public static Item OakBasilisk;
	public static Item BirchAcromantula;
	public static Item OakAcromantula;
	public static Item UnicornHair;
	public static Item BirchUnicorn;
	public static Item OakUnicorn;
	public static Item BillywigStinger;
	public static Item BirchBillywig;
	public static Item OakBillywig;
	public static Item FairyWing;
	public static Item BirchFairy;
	public static Item OakFairy;
	public static Item AugureyFeather;
	public static Item BirchAugurey;
	public static Item OakAugurey;
	public static Item BoomslangVenom;
	public static Item BirchBoomslang;
	public static Item OakBoomslang;
	public static Item ErumpentHide;
	public static Item BirchErumpent;
	public static Item OakErumpent;
	public static Item KelpieHair;
	public static Item BirchKelpie;
	public static Item OakKelpie;
	public static Item DemiguiseHair;
	public static Item BirchDemiguise;
	public static Item OakDemiguise;
	public static Item VeelaHair;
	public static Item BirchVeela;
	public static Item OakVeela;
	public static Item DoxyWing;
	public static Item BirchDoxy;
	public static Item OakDoxy;
	public static Item FwooperFeather;
	public static Item BirchFwooper;
	public static Item OakFwooper;
	public static Item ChimaeraScaleFragment;
	public static Item BirchChimaera;
	public static Item OakChimaera;
	public static Item RowanStick;
	public static Item RowanPhoenix;
	public static Item Galleon;
	public static Item Knut;
	public static Item Sickle;
	public static Item InvisibilityCloak;
	public static Item DPSWandClass;
	public static Item TankWandClass;
	public static Item SupportWandClass;
	public static Item Gillyweed;
	public static Item Bean1;
	public static Item Bean2;
	public static Item Bean3;
	public static Item Bean4;
	public static Item Bean5;
	public static Item Bean6;
	public static Item Bean7;
	public static Item Bean8;
	public static Item Bean9;
	public static Item Bean10;
	public static Item ChocolateFrog;
	public static Item TimeTurner;
	public static Item ButterBeer;
	public static Item TeboRaw;
	public static Item TeboCooked;
	public static Item NogtailRaw;
	public static Item NogtailCooked;
	public static Item RamoraRaw;
	public static Item RamoraCooked;
	public static Item SwordofGryffindor;
	public static Item Trident;
	public static Item AurorLegs;
	public static Item AurorChest;
	public static Item AurorHat;
	public static Item AurorShoes;
	public static Item DeathEaterLegs;
	public static Item DeathEaterChest;
	public static Item DeathEaterHat;
	public static Item DeathEaterShoes;
	public static Item WerewolfLegs;
	public static Item WerewolfChest;
	public static Item WerewolfHead;
	public static Item WerewolfFeet;

	public MainClass() {

	}

	@Mod.EventHandler
	public void Init(final FMLInitializationEvent event) {

		GameRegistry.addRecipe(new ItemStack(MainClass.Gillyweed, 1), new Object[] { " O ", " X ", "   ", 'X', Items.wheat, 'O', Items.glass_bottle });
		GameRegistry.addRecipe(new ItemStack(MainClass.EveryFlavourBeans, 1), new Object[] { "XXX", "XOX", "XXX", 'X', Items.paper, 'O', Items.apple });
		GameRegistry.addRecipe(new ItemStack(MainClass.ChocolateFrog, 1), new Object[] { "XXX", "XOX", "XXX", 'X', Items.paper, 'O', Items.cake });
		GameRegistry.addRecipe(new ItemStack(MainClass.TimeTurner, 1), new Object[] { "   ", " x ", " O ", 'x', Items.gold_ingot, 'O', Items.clock });
		GameRegistry.addRecipe(new ItemStack(MainClass.Bat, 1), new Object[] { "   ", " O ", " x ", 'x', Items.stick, 'O', Blocks.planks });
		GameRegistry.addRecipe(new ItemStack(MainClass.Crystalball, 1), new Object[] { "   ", " x ", " O ", 'x', Blocks.glass, 'O', Blocks.obsidian });
		GameRegistry.addRecipe(new ItemStack(MainClass.MagicBook, 1), new Object[] { "xxx", "xOx", "xxx", 'x', Items.glowstone_dust, 'O', Items.book });
		GameRegistry.addRecipe(new ItemStack(MainClass.MonsterBook, 1), new Object[] { "xxx", "xOx", "xxx", 'x', Items.redstone, 'O', Items.book });
		GameRegistry.addRecipe(new ItemStack(MainClass.TheGoldenSnitch, 1), new Object[] { "x x", " o ", "   ", 'x', MainClass.SilverIngot, 'o', Items.gold_ingot });
		GameRegistry.addRecipe(new ItemStack(MainClass.Quaffle, 1), new Object[] { "xxx", "xOx", "xxx", 'x', Items.leather, 'O', Blocks.wool });
		GameRegistry.addRecipe(new ItemStack(MainClass.Bludger, 1), new Object[] { "xxx", "xOx", "xxx", 'x', Items.leather, 'O', Blocks.iron_block });
		GameRegistry.addRecipe(new ItemStack(MainClass.FordAnglia, 1), new Object[] { "xxx", "OOO", "xIx", 'x', Blocks.wool, 'O', Blocks.glass, 'I', Items.minecart });
		GameRegistry.addRecipe(new ItemStack(MainClass.Motercycle, 1), new Object[] { "  O", " x ", "O O", 'x', Items.minecart, 'O', Blocks.wool });
		GameRegistry.addRecipe(new ItemStack(MainClass.Motercycle2, 1), new Object[] { "   ", "   ", "Ox ", 'x', MainClass.Motercycle, 'O', Items.minecart });
		GameRegistry.addRecipe(new ItemStack(MainClass.Broomstick, 1), new Object[] { "x  ", " x ", "  o", 'x', Items.stick, 'o', Items.wheat });
		GameRegistry.addRecipe(new ItemStack(MainClass.Broomstick, 1), new Object[] { "  x", " x ", "o  ", 'x', Items.stick, 'o', Items.wheat });
		GameRegistry.addRecipe(new ItemStack(MainClass.Broomstick, 1), new Object[] { "o  ", " x ", "  x", 'x', Items.stick, 'o', Items.wheat });
		GameRegistry.addRecipe(new ItemStack(MainClass.Broomstick, 1), new Object[] { "  o", " x ", "x  ", 'x', Items.stick, 'o', Items.wheat });
		GameRegistry.addRecipe(new ItemStack(MainClass.MaraudersMap, 1), new Object[] { "xxx", "xxx", "xxx", 'x', Items.map, 'o', Items.wheat });
		GameRegistry.addRecipe(new ItemStack(MainClass.WerewolfForm, 1), new Object[] { "xxx", "xox", "xxx", 'x', Items.gold_ingot, 'o', Items.clock });
		GameRegistry.addRecipe(new ItemStack(MainClass.OakStick, 1), new Object[] { " ", "x", "x", 'x', new ItemStack(Blocks.log, 1, 0) });
		GameRegistry.addRecipe(new ItemStack(MainClass.BirchStick, 1), new Object[] { " ", "x", "x", 'x', new ItemStack(Blocks.log, 1, 2) });
		GameRegistry.addRecipe(new ItemStack(MainClass.WandCrafterIdle, 1), new Object[] { "  x", "ooo", "zcz", 'x', Items.blaze_rod, 'o', Blocks.carpet, 'z', Blocks.obsidian, 'c', Items.nether_star });
		GameRegistry.addRecipe(new ItemStack(MainClass.Cabinet, 1), new Object[] { "zzz", "ooo", "oco", 'o', Blocks.planks, 'c', Blocks.oak_door, 'z', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.BoggartChestLocked, 1), new Object[] { "zzz", "zzz", "zcz", 'c', Blocks.chest, 'z', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.Penknife, 1), new Object[] { " l ", " O ", " x ", 'x', Items.stick, 'O', Items.iron_ingot, 'l', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.ItemStore, 1), new Object[] { "lll", "lOl", "lll", 'l', Items.leather, 'O', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.PensievePlane, 1), new Object[] { "O O", "lOl", " l ", 'l', Blocks.glass, 'O', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.Pensieve, 1), new Object[] { "   ", "lOl", "lll", 'l', Blocks.sandstone, 'O', MainClass.PensievePlane });
		GameRegistry.addRecipe(new ItemStack(MainClass.ButterBeer, 1), new Object[] { "OlO", "OlO", "OOO", 'O', Blocks.glass, 'l', Items.milk_bucket });
		GameRegistry.addRecipe(new ItemStack(MainClass.Hat, 1), new Object[] { " l ", "lll", "l l", 'l', Items.leather });
		GameRegistry.addRecipe(new ItemStack(MainClass.MirrorShard, 1), new Object[] { "   ", "   ", " l ", 'l', Blocks.glass_pane });
		GameRegistry.addRecipe(new ItemStack(MainClass.Key, 1), new Object[] { " O ", "lOl", " O ", 'l', Blocks.wool, 'O', Items.iron_ingot });
		GameRegistry.addRecipe(new ItemStack(MainClass.MasterKey, 1), new Object[] { " O ", "lOl", " O ", 'l', Blocks.lapis_block, 'O', Items.iron_ingot });
		GameRegistry.addRecipe(new ItemStack(MainClass.Remembrall, 1), new Object[] { "lll", "lOl", "lll", 'l', Blocks.glass, 'O', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.PutOuter, 1), new Object[] { " l ", " O ", " n ", 'l', Items.glowstone_dust, 'O', MainClass.MagicPower, 'n', Blocks.obsidian });
		GameRegistry.addRecipe(new ItemStack(MainClass.Mirror, 1), new Object[] { "nln", "nln", "nln", 'l', Blocks.glass_pane, 'n', Blocks.gold_block });
		GameRegistry.addRecipe(new ItemStack(MainClass.Hat, 1), new Object[] { "   ", "   ", " l ", 'l', Items.rotten_flesh });
		GameRegistry.addRecipe(new ItemStack(MainClass.TriCup, 1), new Object[] { "OmO", " l ", "lll", 'l', Items.iron_ingot, 'm', MainClass.MagicPower, 'O', Blocks.glass_pane });
		GameRegistry.addRecipe(new ItemStack(MainClass.GOF, 1), new Object[] { "lml", " l ", "lll", 'l', Blocks.sandstone, 'm', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.BlackMarbleBrick, 1), new Object[] { " ", " ", "l", 'l', MainClass.BlackMarble });
		GameRegistry.addRecipe(new ItemStack(MainClass.BlackMarbleBrick, 1), new Object[] { " ", "l", " ", 'l', MainClass.BlackMarble });
		GameRegistry.addRecipe(new ItemStack(MainClass.BlackMarbleBrick, 1), new Object[] { "l", " ", " ", 'l', MainClass.BlackMarble });
		GameRegistry.addRecipe(new ItemStack(MainClass.MarblePillar, 1), new Object[] { " ", " ", "l", 'l', MainClass.SmoothMarble });
		GameRegistry.addRecipe(new ItemStack(MainClass.MarblePillar, 1), new Object[] { " ", "l", " ", 'l', MainClass.SmoothMarble });
		GameRegistry.addRecipe(new ItemStack(MainClass.MarblePillar, 1), new Object[] { "l", " ", " ", 'l', MainClass.SmoothMarble });
		GameRegistry.addRecipe(new ItemStack(MainClass.Brick, 1), new Object[] { " ", " ", "l", 'l', Blocks.brick_block });
		GameRegistry.addRecipe(new ItemStack(MainClass.Brick, 1), new Object[] { " ", "l", " ", 'l', Blocks.brick_block });
		GameRegistry.addRecipe(new ItemStack(MainClass.Brick, 1), new Object[] { "l", " ", " ", 'l', Blocks.brick_block });
		GameRegistry.addRecipe(new ItemStack(MainClass.StoneSoldierBlock, 1), new Object[] { "l", "k", "j", 'l', Items.iron_helmet, 'k', MainClass.Brick, 'j', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.AurorHat, 1), new Object[] { " x ", "xyx", "x x", 'x', Items.leather, 'y', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.AurorChest, 1), new Object[] { "z z", "xyx", "xxx", 'x', Items.leather, 'y', MainClass.MagicPower, 'z', Items.iron_ingot });
		GameRegistry.addRecipe(new ItemStack(MainClass.AurorLegs, 1), new Object[] { "xyx", "xxx", "xxx", 'x', Items.leather, 'y', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.AurorShoes, 1), new Object[] { "y y", "x x", 'x', Items.leather, 'y', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.DeathEaterHat, 1), new Object[] { "xxx", "xzx", "xyx", 'x', Blocks.obsidian, 'y', MainClass.MagicPower, 'z', Items.iron_ingot });
		GameRegistry.addRecipe(new ItemStack(MainClass.DeathEaterChest, 1), new Object[] { "z z", "xyx", "xxx", 'x', Blocks.obsidian, 'y', MainClass.MagicPower, 'z', Items.iron_ingot });
		GameRegistry.addRecipe(new ItemStack(MainClass.DeathEaterLegs, 1), new Object[] { "xyx", "xxx", "xxx", 'x', Blocks.obsidian, 'y', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.DeathEaterShoes, 1), new Object[] { "y y", "x x", 'x', Blocks.obsidian, 'y', MainClass.MagicPower });
		GameRegistry.addSmelting(MainClass.TeboRaw, new ItemStack(MainClass.TeboCooked), 10.0f);
		GameRegistry.addSmelting(MainClass.SilverOre, new ItemStack(MainClass.SilverIngot), 20.0f);
		GameRegistry.addSmelting(MainClass.NogtailRaw, new ItemStack(MainClass.NogtailCooked), 9.0f);
		GameRegistry.addSmelting(MainClass.RamoraRaw, new ItemStack(MainClass.RamoraCooked), 9.0f);
		GameRegistry.addSmelting(MainClass.Marble, new ItemStack(MainClass.SmoothMarble), 3.0f);
		GameRegistry.addSmelting(MainClass.BlackMarble, new ItemStack(MainClass.SmoothBlackMarble), 3.0f);

		if (event.getSide() == Side.CLIENT) {

			RenderItem renderItem = Minecraft.getMinecraft().getRenderItem();

			renderItem.getItemModelMesher().register(AugureyFeather, 0, new ModelResourceLocation(MODID + ":" + ((AugureyFeatherClass) AugureyFeather).getName(), "inventory"));
			renderItem.getItemModelMesher().register(BasiliskScale, 0, new ModelResourceLocation(MODID + ":" + ((BasiliskScaleClass) BasiliskScale).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Bat, 0, new ModelResourceLocation(MODID + ":" + ((BatClass) Bat).getName(), "inventory"));
			renderItem.getItemModelMesher().register(BFang, 0, new ModelResourceLocation(MODID + ":" + ((BFangClass) BFang).getName(), "inventory"));
			renderItem.getItemModelMesher().register(BillywigStinger, 0, new ModelResourceLocation(MODID + ":" + ((BillywigStingerClass) BillywigStinger).getName(), "inventory"));
			renderItem.getItemModelMesher().register(BirchStick, 0, new ModelResourceLocation(MODID + ":" + ((BirchStickClass) BirchStick).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Bludger, 0, new ModelResourceLocation(MODID + ":" + ((BludgerClass) Bludger).getName(), "inventory"));
			renderItem.getItemModelMesher().register(BoomslangVenom, 0, new ModelResourceLocation(MODID + ":" + ((BoomslangVenomClass) BoomslangVenom).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Broomstick, 0, new ModelResourceLocation(MODID + ":" + ((BroomstickClass) Broomstick).getName(), "inventory"));
			renderItem.getItemModelMesher().register(ChimaeraScaleFragment, 0, new ModelResourceLocation(MODID + ":" + ((ChimaeraScaleFragmentClass) ChimaeraScaleFragment).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Deluminator, 0, new ModelResourceLocation(MODID + ":" + ((DeluminatorClass) Deluminator).getName(), "inventory"));
			renderItem.getItemModelMesher().register(DemiguiseHair, 0, new ModelResourceLocation(MODID + ":" + ((DemiguiseHairClass) DemiguiseHair).getName(), "inventory"));
			renderItem.getItemModelMesher().register(DoxyWing, 0, new ModelResourceLocation(MODID + ":" + ((DoxyWingClass) DoxyWing).getName(), "inventory"));
			renderItem.getItemModelMesher().register(DragonHeartString, 0, new ModelResourceLocation(MODID + ":" + ((DragonHeartStringClass) DragonHeartString).getName(), "inventory"));
			renderItem.getItemModelMesher().register(ElderWand, 0, new ModelResourceLocation(MODID + ":" + ((ElderWandClass) ElderWand).getName(), "inventory"));
			renderItem.getItemModelMesher().register(ErumpentHide, 0, new ModelResourceLocation(MODID + ":" + ((ErumpentHideClass) ErumpentHide).getName(), "inventory"));
			renderItem.getItemModelMesher().register(FairyWing, 0, new ModelResourceLocation(MODID + ":" + ((FairyWingClass) FairyWing).getName(), "inventory"));
			renderItem.getItemModelMesher().register(FordAnglia, 0, new ModelResourceLocation(MODID + ":" + ((FordAngliaClass) FordAnglia).getName(), "inventory"));
			renderItem.getItemModelMesher().register(FwooperFeather, 0, new ModelResourceLocation(MODID + ":" + ((FwooperFeatherClass) FwooperFeather).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Galleon, 0, new ModelResourceLocation(MODID + ":" + ((GalleonClass) Galleon).getName(), "inventory"));
			renderItem.getItemModelMesher().register(HippogriffFeather, 0, new ModelResourceLocation(MODID + ":" + ((HippogriffFeatherClass) HippogriffFeather).getName(), "inventory"));
			renderItem.getItemModelMesher().register(ItemStore, 0, new ModelResourceLocation(MODID + ":" + ((ItemStoreClass) ItemStore).getName(), "inventory"));
			renderItem.getItemModelMesher().register(KelpieHair, 0, new ModelResourceLocation(MODID + ":" + ((KelpieHairClass) KelpieHair).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Key, 0, new ModelResourceLocation(MODID + ":" + ((KeyClass) Key).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Knut, 0, new ModelResourceLocation(MODID + ":" + ((KnutClass) Knut).getName(), "inventory"));
			renderItem.getItemModelMesher().register(MagicBook, 0, new ModelResourceLocation(MODID + ":" + ((MagicBookClass) MagicBook).getName(), "inventory"));
			renderItem.getItemModelMesher().register(MagicPower, 0, new ModelResourceLocation(MODID + ":" + ((MagicPowderClass) MagicPower).getName(), "inventory"));
			renderItem.getItemModelMesher().register(MaraudersMap, 0, new ModelResourceLocation(MODID + ":" + ((MaraudersMapClass) MaraudersMap).getName(), "inventory"));
			renderItem.getItemModelMesher().register(MasterKey, 0, new ModelResourceLocation(MODID + ":" + ((MasterKeyClass) MasterKey).getName(), "inventory"));
			renderItem.getItemModelMesher().register(MirrorShard, 0, new ModelResourceLocation(MODID + ":" + ((MirrorShardClass) MirrorShard).getName(), "inventory"));
			renderItem.getItemModelMesher().register(MonsterBook, 0, new ModelResourceLocation(MODID + ":" + ((MonsterBookClass) MonsterBook).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Motercycle2, 0, new ModelResourceLocation(MODID + ":" + ((Motercycle2Class) Motercycle2).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Motercycle, 0, new ModelResourceLocation(MODID + ":" + ((MotercycleClass) Motercycle).getName(), "inventory"));
			renderItem.getItemModelMesher().register(OakStick, 0, new ModelResourceLocation(MODID + ":" + ((OakStickClass) OakStick).getName(), "inventory"));
			renderItem.getItemModelMesher().register(PStone, 0, new ModelResourceLocation(MODID + ":" + ((PStoneClass) PStone).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Penknife, 0, new ModelResourceLocation(MODID + ":" + ((PenknifeClass) Penknife).getName(), "inventory"));
			renderItem.getItemModelMesher().register(PhoenixFeather, 0, new ModelResourceLocation(MODID + ":" + ((PhoenixFeatherClass) PhoenixFeather).getName(), "inventory"));
			renderItem.getItemModelMesher().register(PutOuter, 0, new ModelResourceLocation(MODID + ":" + ((PutOuterClass) PutOuter).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Quaffle, 0, new ModelResourceLocation(MODID + ":" + ((QuaffleClass) Quaffle).getName(), "inventory"));
			renderItem.getItemModelMesher().register(RStone, 0, new ModelResourceLocation(MODID + ":" + ((RStoneClass) RStone).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Remembrall, 0, new ModelResourceLocation(MODID + ":" + ((RemembrallClass) Remembrall).getName(), "inventory"));
			renderItem.getItemModelMesher().register(RowanStick, 0, new ModelResourceLocation(MODID + ":" + ((RowanStickClass) RowanStick).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Ruby, 0, new ModelResourceLocation(MODID + ":" + ((RubyClass) Ruby).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Sickle, 0, new ModelResourceLocation(MODID + ":" + ((SickleClass) Sickle).getName(), "inventory"));
			renderItem.getItemModelMesher().register(SilverIngot, 0, new ModelResourceLocation(MODID + ":" + ((SilverIngotClass) SilverIngot).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Sock, 0, new ModelResourceLocation(MODID + ":" + ((SockClass) Sock).getName(), "inventory"));
			renderItem.getItemModelMesher().register(TheGoldenSnitch, 0, new ModelResourceLocation(MODID + ":" + ((TheGoldenSnitchClass) TheGoldenSnitch).getName(), "inventory"));
			renderItem.getItemModelMesher().register(TimeTurner, 0, new ModelResourceLocation(MODID + ":" + ((TimeTurnerClass) TimeTurner).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Trident, 0, new ModelResourceLocation(MODID + ":" + ((TridentClass) Trident).getName(), "inventory"));
			renderItem.getItemModelMesher().register(UnicornHair, 0, new ModelResourceLocation(MODID + ":" + ((UnicornHairClass) UnicornHair).getName(), "inventory"));
			renderItem.getItemModelMesher().register(VeelaHair, 0, new ModelResourceLocation(MODID + ":" + ((VeelaHairClass) VeelaHair).getName(), "inventory"));
			renderItem.getItemModelMesher().register(WerewolfForm, 0, new ModelResourceLocation(MODID + ":" + ((WerewolfFormClass) WerewolfForm).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Bean1, 0, new ModelResourceLocation(MODID + ":" + ((Bean1Class) Bean1).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Bean2, 0, new ModelResourceLocation(MODID + ":" + ((Bean2Class) Bean2).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Bean3, 0, new ModelResourceLocation(MODID + ":" + ((Bean3Class) Bean3).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Bean4, 0, new ModelResourceLocation(MODID + ":" + ((Bean4Class) Bean4).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Bean5, 0, new ModelResourceLocation(MODID + ":" + ((Bean5Class) Bean5).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Bean6, 0, new ModelResourceLocation(MODID + ":" + ((Bean6Class) Bean6).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Bean7, 0, new ModelResourceLocation(MODID + ":" + ((Bean7Class) Bean7).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Bean8, 0, new ModelResourceLocation(MODID + ":" + ((Bean8Class) Bean8).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Bean9, 0, new ModelResourceLocation(MODID + ":" + ((Bean9Class) Bean9).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Bean10, 0, new ModelResourceLocation(MODID + ":" + ((Bean10Class) Bean10).getName(), "inventory"));
			renderItem.getItemModelMesher().register(ChocolateFrog, 0, new ModelResourceLocation(MODID + ":" + ((ChocolateFrogClass) ChocolateFrog).getName(), "inventory"));
			renderItem.getItemModelMesher().register(ButterBeer, 0, new ModelResourceLocation(MODID + ":" + ((ButterBeerClass) ButterBeer).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Gillyweed, 0, new ModelResourceLocation(MODID + ":" + ((GillyweedClass) Gillyweed).getName(), "inventory"));
			renderItem.getItemModelMesher().register(NogtailCooked, 0, new ModelResourceLocation(MODID + ":" + ((NogtailCookedClass) NogtailCooked).getName(), "inventory"));
			renderItem.getItemModelMesher().register(NogtailRaw, 0, new ModelResourceLocation(MODID + ":" + ((NogtailRawClass) NogtailRaw).getName(), "inventory"));
			renderItem.getItemModelMesher().register(RamoraCooked, 0, new ModelResourceLocation(MODID + ":" + ((RamoraCookedClass) RamoraCooked).getName(), "inventory"));
			renderItem.getItemModelMesher().register(RamoraRaw, 0, new ModelResourceLocation(MODID + ":" + ((RamoraRawClass) RamoraRaw).getName(), "inventory"));
			renderItem.getItemModelMesher().register(TeboCooked, 0, new ModelResourceLocation(MODID + ":" + ((TeboCookedClass) TeboCooked).getName(), "inventory"));
			renderItem.getItemModelMesher().register(TeboRaw, 0, new ModelResourceLocation(MODID + ":" + ((TeboRawClass) TeboRaw).getName(), "inventory"));
			renderItem.getItemModelMesher().register(DPSWandClass, 0, new ModelResourceLocation(MODID + ":" + ((DPSWandClass) DPSWandClass).getName(), "inventory"));
			renderItem.getItemModelMesher().register(SupportWandClass, 0, new ModelResourceLocation(MODID + ":" + ((SupportWandClass) SupportWandClass).getName(), "inventory"));
			renderItem.getItemModelMesher().register(TankWandClass, 0, new ModelResourceLocation(MODID + ":" + ((TankWandClass) TankWandClass).getName(), "inventory"));
			renderItem.getItemModelMesher().register(SwordofGryffindor, 0, new ModelResourceLocation(MODID + ":" + ((SwordofGryffindorClass) SwordofGryffindor).getName(), "inventory"));
			renderItem.getItemModelMesher().register(InvisibilityCloak, 0, new ModelResourceLocation(MODID + ":" + ((InvisibilityCloakArmorClass) InvisibilityCloak).getName(), "inventory"));
			renderItem.getItemModelMesher().register(AurorLegs, 0, new ModelResourceLocation(MODID + ":AurorLegs", "inventory"));
			renderItem.getItemModelMesher().register(AurorChest, 0, new ModelResourceLocation(MODID + ":AurorChest", "inventory"));
			renderItem.getItemModelMesher().register(AurorHat, 0, new ModelResourceLocation(MODID + ":AurorHat", "inventory"));
			renderItem.getItemModelMesher().register(AurorShoes, 0, new ModelResourceLocation(MODID + ":AurorShoes", "inventory"));
			renderItem.getItemModelMesher().register(DeathEaterLegs, 0, new ModelResourceLocation(MODID + ":DeathEaterLegs", "inventory"));
			renderItem.getItemModelMesher().register(DeathEaterChest, 0, new ModelResourceLocation(MODID + ":DeathEaterChest", "inventory"));
			renderItem.getItemModelMesher().register(DeathEaterHat, 0, new ModelResourceLocation(MODID + ":DeathEaterHat", "inventory"));
			renderItem.getItemModelMesher().register(DeathEaterShoes, 0, new ModelResourceLocation(MODID + ":DeathEaterShoes", "inventory"));

			renderItem.getItemModelMesher().register(Item.getItemFromBlock(AcromantulaWeb), 0, new ModelResourceLocation(MODID + ":" + ((AcromantulaWebClass) AcromantulaWeb).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(BlackMarbleBrick), 0, new ModelResourceLocation(MODID + ":" + ((BlackMarbleBrickClass) BlackMarbleBrick).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(BlackMarble), 0, new ModelResourceLocation(MODID + ":" + ((BlackMarbleClass) BlackMarble).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(Brick), 0, new ModelResourceLocation(MODID + ":" + ((BrickClass) Brick).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(Marble), 0, new ModelResourceLocation(MODID + ":" + ((MarbleClass) Marble).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(SmoothMarble), 0, new ModelResourceLocation(MODID + ":" + ((SmoothMarbleClass) SmoothMarble).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(SmoothBlackMarble), 0, new ModelResourceLocation(MODID + ":" + ((SmoothBlackMarbleClass) SmoothBlackMarble).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(RubyOre), 0, new ModelResourceLocation(MODID + ":" + ((RubyOreClass) RubyOre).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(StoneSoldierBlock), 0, new ModelResourceLocation(MODID + ":" + ((StoneSoldierBlockClass) StoneSoldierBlock).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(Hat), 0, new ModelResourceLocation(MODID + ":" + ((HatClass) Hat).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(WandCrafterActive), 0, new ModelResourceLocation(MODID + ":" + ((WandCrafterClass) WandCrafterActive).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(WandCrafterIdle), 0, new ModelResourceLocation(MODID + ":" + ((WandCrafterClass) WandCrafterIdle).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(MagicPowerOre), 0, new ModelResourceLocation(MODID + ":" + ((MagicPowerOreClass) MagicPowerOre).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(SilverOre), 0, new ModelResourceLocation(MODID + ":" + ((SilverOreClass) SilverOre).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(MarblePillar), 0, new ModelResourceLocation(MODID + ":" + ((MarblePillarClass) MarblePillar).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(BoggartChestOpen), 0, new ModelResourceLocation(MODID + ":" + ((BoggartChestOpenClass) BoggartChestOpen).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(BoggartChestLocked), 0, new ModelResourceLocation(MODID + ":" + ((BoggartChestLockedClass) BoggartChestLocked).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(Cabinet), 0, new ModelResourceLocation(MODID + ":" + ((CabinetClass) Cabinet).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(Mirror), 0, new ModelResourceLocation(MODID + ":" + ((MirrorClass) Mirror).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(GOF), 0, new ModelResourceLocation(MODID + ":" + ((GOFClass) GOF).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(Hand), 0, new ModelResourceLocation(MODID + ":" + ((HandClass) Hand).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(Ring), 0, new ModelResourceLocation(MODID + ":" + ((RingClass) Ring).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(Locket), 0, new ModelResourceLocation(MODID + ":" + ((LocketClass) Locket).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(Pensieve), 0, new ModelResourceLocation(MODID + ":" + ((PensieveClass) Pensieve).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(Diadem), 0, new ModelResourceLocation(MODID + ":" + ((DiademClass) Diadem).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(GoldenEgg), 0, new ModelResourceLocation(MODID + ":" + ((GoldenEggClass) GoldenEgg).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(GoldenEggOpen), 0, new ModelResourceLocation(MODID + ":" + ((GoldenEggOpenClass) GoldenEggOpen).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(EveryFlavourBeans), 0, new ModelResourceLocation(MODID + ":" + ((EveryFlavourBeansClass) EveryFlavourBeans).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(PensievePlane), 0, new ModelResourceLocation(MODID + ":" + ((PensievePlaneClass) PensievePlane).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(Diary), 0, new ModelResourceLocation(MODID + ":" + ((DiaryClass) Diary).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(TriCup), 0, new ModelResourceLocation(MODID + ":" + ((TriCupClass) TriCup).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(Crystalball), 0, new ModelResourceLocation(MODID + ":" + ((CrystalballClass) Crystalball).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(Cup), 0, new ModelResourceLocation(MODID + ":" + ((CupClass) Cup).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(WingardiumLeviosaBlock), 0, new ModelResourceLocation(MODID + ":" + ((WingardiumLeviosaBlockClass) WingardiumLeviosaBlock).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(BrokenGlass), 0, new ModelResourceLocation(MODID + ":" + ((BrokenGlassClass) BrokenGlass).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(GlowstoneOff), 0, new ModelResourceLocation(MODID + ":" + ((GlowstoneOffClass) GlowstoneOff).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(LampOff), 0, new ModelResourceLocation(MODID + ":" + ((LampOffClass) LampOff).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(Stun), 0, new ModelResourceLocation(MODID + ":" + ((StunClass) Stun).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(DarkMark), 0, new ModelResourceLocation(MODID + ":" + ((DarkMarkClass) DarkMark).getName(), "inventory"));
			renderItem.getItemModelMesher().register(Item.getItemFromBlock(TorchOff), 0, new ModelResourceLocation(MODID + ":" + ((TorchOffClass) TorchOff).getName(), "inventory"));

		}

	}

	@Mod.EventHandler
	public void PreInit(final FMLPreInitializationEvent preEvent) {

		MainClass.SpellTab = new SpellTabClass(CreativeTabs.getNextID(), "Wands");
		MainClass.MagicFood = new MagicFoodClass(CreativeTabs.getNextID(), "MagicFood");
		MainClass.MagicItems = new MagicItemsClass(CreativeTabs.getNextID(), "MagicItems");
		MainClass.MagicMaterials = new MagicMaterialsClass(CreativeTabs.getNextID(), "MagicMaterials");
		MainClass.WandCrafting = new WandCraftingClass(CreativeTabs.getNextID(), "WandCrafting");

		MainClass.MagicWeaponMaterial = EnumHelper.addToolMaterial("MagicWeaponMaterial", 10, 999999999, 20.0f, 9.0f, 0);
		MainClass.MagicArmorMaterial = EnumHelper.addArmorMaterial("MagicArmorMaterial", "harrypottermod:MagicArmor", 999999999, new int[] { 999999999, 999999999, 999999999, 999999999 }, 0);
		MainClass.TridentMaterial = EnumHelper.addToolMaterial("TridentMaterial", 5, 5000, 10.0f, 5.0f, 0);
		MainClass.AurorArmor = EnumHelper.addArmorMaterial("AurorArmor", "harrypottermod:AurorArmor", 100, new int[] { 20, 60, 40, 20 }, 30);
		MainClass.DeathEaterArmor = EnumHelper.addArmorMaterial("DeathEaterArmor", "harrypottermod:DeathEaterArmor", 100, new int[] { 10, 30, 20, 10 }, 0);
		MainClass.WerewolfFur = EnumHelper.addArmorMaterial("WerewolfFur", "harrypottermod:WerewolfArmor", 100, new int[] { 30, 80, 60, 30 }, 0);

		MainClass.ShieldEffect = new ShieldEffectClass(new ResourceLocation("harrypottermod:ShieldEffect"), true, 4866583).setPotionName("potion.Shield.name");
		MainClass.RubyOre = new RubyOreClass(Material.rock).setUnlocalizedName("RubyOre").setCreativeTab(MainClass.MagicMaterials);
		MainClass.SilverOre = new SilverOreClass(Material.rock).setUnlocalizedName("SilverOre").setCreativeTab(MainClass.MagicMaterials);
		MainClass.Brick = new BrickClass(Material.rock).setUnlocalizedName("Brick").setCreativeTab(MainClass.MagicMaterials);
		MainClass.Marble = new MarbleClass(Material.rock).setUnlocalizedName("Marble").setCreativeTab(MainClass.MagicMaterials);
		MainClass.MarblePillar = new MarblePillarClass(Material.rock).setUnlocalizedName("MarblePillar").setCreativeTab(MainClass.MagicMaterials);
		MainClass.BlackMarble = new BlackMarbleClass(Material.rock).setUnlocalizedName("BlackMarble").setCreativeTab(MainClass.MagicMaterials);
		MainClass.SmoothMarble = new SmoothMarbleClass(Material.rock).setUnlocalizedName("SmoothMarble").setCreativeTab(MainClass.MagicMaterials);
		MainClass.SmoothBlackMarble = new SmoothBlackMarbleClass(Material.rock).setUnlocalizedName("SmoothBlackMarble").setCreativeTab(MainClass.MagicMaterials);
		MainClass.BlackMarbleBrick = new BlackMarbleBrickClass(Material.rock).setUnlocalizedName("BlackMarbleBrick").setCreativeTab(MainClass.MagicMaterials);
		MainClass.DarkMark = new DarkMarkClass(Material.glass).setUnlocalizedName("DarkMark");
		MainClass.BrokenGlass = new BrokenGlassClass(Material.glass).setUnlocalizedName("BrokenGlass").setCreativeTab(MainClass.MagicItems);
		MainClass.Stun = new StunClass(Material.web).setUnlocalizedName("Stun").setCreativeTab((CreativeTabs) null);
		MainClass.Cup = new CupClass(Material.iron).setUnlocalizedName("Cup").setCreativeTab(MainClass.MagicItems);
		MainClass.Crystalball = new CrystalballClass(Material.glass).setUnlocalizedName("Crystalball").setCreativeTab(MainClass.MagicItems);
		MainClass.TriCup = new TriCupClass(Material.glass).setUnlocalizedName("TriCup").setCreativeTab(MainClass.MagicItems);
		MainClass.WingardiumLeviosaBlock = new WingardiumLeviosaBlockClass(Material.rock).setUnlocalizedName("WingardiumLeviosaBlock").setCreativeTab(MainClass.MagicItems);
		MainClass.Diadem = new DiademClass(Material.iron).setUnlocalizedName("Diadem").setCreativeTab(MainClass.MagicItems);
		MainClass.Diary = new DiaryClass(Material.wood).setUnlocalizedName("Diary").setCreativeTab(MainClass.MagicItems);
		MainClass.GoldenEgg = new GoldenEggClass(Material.iron).setUnlocalizedName("GoldenEgg").setCreativeTab(MainClass.MagicItems);
		MainClass.GoldenEggOpen = new GoldenEggOpenClass(Material.iron).setUnlocalizedName("GoldenEggOpen").setCreativeTab((CreativeTabs) null);
		MainClass.PensievePlane = new PensievePlaneClass(Material.iron).setUnlocalizedName("PensievePlane").setCreativeTab(MainClass.MagicItems);
		MainClass.Pensieve = new PensieveClass(Material.iron).setUnlocalizedName("Pensieve").setCreativeTab(MainClass.MagicItems);
		MainClass.Locket = new LocketClass(Material.iron).setUnlocalizedName("Locket").setCreativeTab(MainClass.MagicItems);
		MainClass.Ring = new RingClass(Material.iron).setUnlocalizedName("Ring").setCreativeTab(MainClass.MagicItems);
		MainClass.Hand = new HandClass(Material.iron).setUnlocalizedName("Hand").setCreativeTab(MainClass.MagicItems);
		MainClass.Mirror = new MirrorClass(Material.iron).setUnlocalizedName("Mirror").setCreativeTab(MainClass.MagicItems);
		MainClass.TorchOff = new TorchOffClass().setUnlocalizedName("TorchOff").setCreativeTab((CreativeTabs) null);
		MainClass.LampOff = new LampOffClass(Material.glass).setUnlocalizedName("LampOff").setCreativeTab((CreativeTabs) null);
		MainClass.GlowstoneOff = new GlowstoneOffClass(Material.glass).setUnlocalizedName("GlowstoneOff").setCreativeTab((CreativeTabs) null);
		MainClass.GOF = new GOFClass(Material.iron).setUnlocalizedName("GOF").setCreativeTab(MainClass.MagicItems);
		MainClass.Cabinet = new CabinetClass(Material.wood).setUnlocalizedName("Cabinet").setCreativeTab(MainClass.MagicItems);
		MainClass.EveryFlavourBeans = new EveryFlavourBeansClass(Material.wood).setUnlocalizedName("EveryFlavourBeans").setCreativeTab(MainClass.MagicFood);
		MainClass.Hat = new HatClass(Material.cloth).setUnlocalizedName("Hat").setCreativeTab(MainClass.MagicItems);
		MainClass.MagicCauldron = new MagicCauldronClass().setUnlocalizedName("MagicCauldron").setCreativeTab(MainClass.MagicItems);
		MainClass.BoggartChestLocked = new BoggartChestLockedClass(Material.wood).setUnlocalizedName("BoggartChestLocked").setCreativeTab(MainClass.MagicItems);
		MainClass.BoggartChestOpen = new BoggartChestOpenClass(Material.wood).setUnlocalizedName("BoggartChestOpen").setCreativeTab((CreativeTabs) null);
		MainClass.WandCrafterIdle = new WandCrafterClass(false).setUnlocalizedName("WandCrafterIdle").setCreativeTab(MainClass.WandCrafting);
		MainClass.WandCrafterActive = new WandCrafterClass(true).setUnlocalizedName("WandCrafterActive").setCreativeTab((CreativeTabs) null);
		MainClass.MagicPowerOre = new MagicPowerOreClass(Material.rock).setUnlocalizedName("MagicPowerOre").setCreativeTab(MainClass.MagicMaterials);
		MainClass.AcromantulaWeb = new AcromantulaWebClass().setUnlocalizedName("AcromantulaWeb").setCreativeTab(MainClass.WandCrafting);
		MainClass.StoneSoldierBlock = new StoneSoldierBlockClass(Material.rock).setUnlocalizedName("StoneSoldierBlock").setCreativeTab(MainClass.MagicItems);
		MainClass.SilverIngot = new SilverIngotClass().setUnlocalizedName("SilverIngot").setCreativeTab(MainClass.MagicMaterials);
		MainClass.Ruby = new RubyClass().setUnlocalizedName("Ruby").setCreativeTab(MainClass.MagicMaterials);
		MainClass.Bat = new BatClass().setUnlocalizedName("Bat").setCreativeTab(MainClass.MagicItems);
		MainClass.MagicBook = new MagicBookClass().setUnlocalizedName("MagicBook").setCreativeTab(MainClass.MagicItems);
		MainClass.MonsterBook = new MonsterBookClass().setUnlocalizedName("MonsterBook").setCreativeTab(MainClass.MagicItems);
		MainClass.TheGoldenSnitch = new TheGoldenSnitchClass().setUnlocalizedName("TheGoldenSnitch").setCreativeTab(MainClass.MagicItems);
		MainClass.Quaffle = new QuaffleClass().setUnlocalizedName("Quaffle").setCreativeTab(MainClass.MagicItems);
		MainClass.Bludger = new BludgerClass().setUnlocalizedName("Bludger").setCreativeTab(MainClass.MagicItems);
		MainClass.FordAnglia = new FordAngliaClass().setUnlocalizedName("FordAnglia").setCreativeTab(MainClass.MagicItems);
		MainClass.Motercycle = new MotercycleClass().setUnlocalizedName("Motercycle").setCreativeTab(MainClass.MagicItems);
		MainClass.Motercycle2 = new Motercycle2Class().setUnlocalizedName("Motercycle2").setCreativeTab(MainClass.MagicItems);
		MainClass.Broomstick = new BroomstickClass().setUnlocalizedName("Broomstick").setCreativeTab(MainClass.MagicItems);
		MainClass.MaraudersMap = new MaraudersMapClass().setUnlocalizedName("MaraudersMap").setCreativeTab(MainClass.MagicItems);
		MainClass.WerewolfForm = new WerewolfFormClass().setUnlocalizedName("WerewolfForm").setCreativeTab(MainClass.MagicItems);
		MainClass.PhoenixFeather = new PhoenixFeatherClass().setUnlocalizedName("PhoenixFeather").setCreativeTab(MainClass.WandCrafting);
		MainClass.PStone = new PStoneClass().setUnlocalizedName("PStone").setCreativeTab(MainClass.MagicItems);
		MainClass.Deluminator = new DeluminatorClass().setUnlocalizedName("Deluminator").setCreativeTab((CreativeTabs) null);
		MainClass.PutOuter = new PutOuterClass().setUnlocalizedName("PutOuter").setCreativeTab(MainClass.MagicItems);
		MainClass.Penknife = new PenknifeClass().setUnlocalizedName("Penknife").setCreativeTab(MainClass.MagicItems);
		MainClass.ItemStore = new ItemStoreClass().setUnlocalizedName("ItemStore").setCreativeTab(MainClass.MagicItems);
		MainClass.Key = new KeyClass().setUnlocalizedName("Key").setCreativeTab(MainClass.MagicItems);
		MainClass.MasterKey = new MasterKeyClass().setUnlocalizedName("MasterKey").setCreativeTab(MainClass.MagicItems);
		MainClass.RStone = new RStoneClass().setUnlocalizedName("RStone").setCreativeTab(MainClass.MagicItems);
		MainClass.ElderWand = new ElderWandClass().setUnlocalizedName("ElderWand").setCreativeTab(MainClass.SpellTab);
		MainClass.BFang = new BFangClass().setUnlocalizedName("BFang").setCreativeTab(MainClass.MagicItems);
		MainClass.MirrorShard = new MirrorShardClass().setUnlocalizedName("MirrorShard").setCreativeTab(MainClass.MagicItems);
		MainClass.Sock = new SockClass().setUnlocalizedName("Sock").setCreativeTab(MainClass.MagicItems);
		MainClass.HippogriffFeather = new HippogriffFeatherClass().setUnlocalizedName("HippogriffFeather").setCreativeTab(MainClass.WandCrafting);
		MainClass.Remembrall = new RemembrallClass().setUnlocalizedName("Remembrall").setCreativeTab(MainClass.MagicItems);
		MainClass.OakStick = new OakStickClass().setUnlocalizedName("OakStick").setCreativeTab(MainClass.WandCrafting);
		MainClass.BirchStick = new BirchStickClass().setUnlocalizedName("BirchStick").setCreativeTab(MainClass.WandCrafting);
		MainClass.MagicPower = new MagicPowderClass().setUnlocalizedName("MagicPower").setCreativeTab(MainClass.WandCrafting);
		MainClass.DragonHeartString = new DragonHeartStringClass().setUnlocalizedName("DragonHeartString").setCreativeTab(MainClass.WandCrafting);
		MainClass.BasiliskScale = new BasiliskScaleClass().setUnlocalizedName("BasiliskScale").setCreativeTab(MainClass.WandCrafting);
		MainClass.UnicornHair = new UnicornHairClass().setUnlocalizedName("UnicornHair").setCreativeTab(MainClass.WandCrafting);
		MainClass.BillywigStinger = new BillywigStingerClass().setUnlocalizedName("BillywigStinger").setCreativeTab(MainClass.WandCrafting);
		MainClass.FairyWing = new FairyWingClass().setUnlocalizedName("FairyWing").setCreativeTab(MainClass.WandCrafting);
		MainClass.AugureyFeather = new AugureyFeatherClass().setUnlocalizedName("AugureyFeather").setCreativeTab(MainClass.WandCrafting);
		MainClass.BoomslangVenom = new BoomslangVenomClass().setUnlocalizedName("BoomslangVenom").setCreativeTab(MainClass.WandCrafting);
		MainClass.ErumpentHide = new ErumpentHideClass().setUnlocalizedName("ErumpentHide").setCreativeTab(MainClass.WandCrafting);
		MainClass.KelpieHair = new KelpieHairClass().setUnlocalizedName("KelpieHair").setCreativeTab(MainClass.WandCrafting);
		MainClass.DemiguiseHair = new DemiguiseHairClass().setUnlocalizedName("DemiguiseHair").setCreativeTab(MainClass.WandCrafting);
		MainClass.VeelaHair = new VeelaHairClass().setUnlocalizedName("VeelaHair").setCreativeTab(MainClass.WandCrafting);
		MainClass.DoxyWing = new DoxyWingClass().setUnlocalizedName("DoxyWing").setCreativeTab(MainClass.WandCrafting);
		MainClass.FwooperFeather = new FwooperFeatherClass().setUnlocalizedName("FwooperFeather").setCreativeTab(MainClass.WandCrafting);
		MainClass.ChimaeraScaleFragment = new ChimaeraScaleFragmentClass().setUnlocalizedName("ChimaeraScaleFragment").setCreativeTab(MainClass.WandCrafting);
		MainClass.RowanStick = new RowanStickClass().setUnlocalizedName("RowanStick").setCreativeTab(MainClass.WandCrafting);
		MainClass.Galleon = new GalleonClass().setUnlocalizedName("Galleon").setCreativeTab(MainClass.MagicItems);
		MainClass.Knut = new KnutClass().setUnlocalizedName("Knut").setCreativeTab(MainClass.MagicItems);
		MainClass.Sickle = new SickleClass().setUnlocalizedName("Sickle").setCreativeTab(MainClass.MagicItems);
		MainClass.InvisibilityCloak = new InvisibilityCloakArmorClass(MainClass.MagicArmorMaterial, MainClass.InvisibilityCloakID, 1).setUnlocalizedName("InvisibilityCloak").setCreativeTab(MainClass.MagicItems);
		MainClass.DPSWandClass = new DPSWandClass().setUnlocalizedName("DPSWandClass").setCreativeTab(MainClass.SpellTab);
		MainClass.TankWandClass = new TankWandClass().setUnlocalizedName("TankWandClass").setCreativeTab(MainClass.SpellTab);
		MainClass.SupportWandClass = new SupportWandClass().setUnlocalizedName("SupportWandClass").setCreativeTab(MainClass.SpellTab);
		MainClass.Gillyweed = new GillyweedClass(999999999, 1.0E9f, false).setPotionEffect(Potion.waterBreathing.id, 3600, 1, 0.8f).setUnlocalizedName("Gillyweed").setCreativeTab(MainClass.MagicFood);
		MainClass.Bean1 = new Bean1Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean1").setCreativeTab((CreativeTabs) null);
		MainClass.Bean2 = new Bean2Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean2").setCreativeTab((CreativeTabs) null);
		MainClass.Bean3 = new Bean3Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean3").setCreativeTab((CreativeTabs) null);
		MainClass.Bean4 = new Bean4Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean4").setCreativeTab((CreativeTabs) null);
		MainClass.Bean5 = new Bean5Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean5").setCreativeTab((CreativeTabs) null);
		MainClass.Bean6 = new Bean6Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean6").setCreativeTab((CreativeTabs) null);
		MainClass.Bean7 = new Bean7Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean7").setCreativeTab((CreativeTabs) null);
		MainClass.Bean8 = new Bean8Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean8").setCreativeTab((CreativeTabs) null);
		MainClass.Bean9 = new Bean9Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean9").setCreativeTab((CreativeTabs) null);
		MainClass.Bean10 = new Bean10Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean10").setCreativeTab((CreativeTabs) null);
		MainClass.ChocolateFrog = new ChocolateFrogClass(999999999, 1.0E9f, false).setUnlocalizedName("ChocolateFrog").setCreativeTab(MainClass.MagicFood);
		MainClass.TimeTurner = new TimeTurnerClass(0, 1.0f, false).setUnlocalizedName("TimeTurner").setCreativeTab(MainClass.MagicItems);
		MainClass.ButterBeer = new ButterBeerClass(999999999, 1.0E9f, false).setPotionEffect(Potion.confusion.id, 30, 1, 0.8f).setUnlocalizedName("ButterBeer").setCreativeTab(MainClass.MagicFood);
		MainClass.TeboRaw = new TeboRawClass(2, 2.0f, false).setPotionEffect(Potion.hunger.id, 30, 1, 0.8f).setUnlocalizedName("TeboRaw").setCreativeTab(MainClass.MagicFood);
		MainClass.TeboCooked = new TeboCookedClass(999999999, 1.0E9f, false).setUnlocalizedName("TeboCooked").setCreativeTab(MainClass.MagicFood);
		MainClass.NogtailRaw = new NogtailRawClass(2, 2.0f, false).setPotionEffect(Potion.hunger.id, 30, 1, 0.8f).setUnlocalizedName("NogtailRaw").setCreativeTab(MainClass.MagicFood);
		MainClass.NogtailCooked = new NogtailCookedClass(999999999, 1.0E9f, false).setUnlocalizedName("NogtailCooked").setCreativeTab(MainClass.MagicFood);
		MainClass.RamoraRaw = new RamoraRawClass(2, 2.0f, false).setPotionEffect(Potion.hunger.id, 30, 1, 0.8f).setUnlocalizedName("RamoraRaw").setCreativeTab(MainClass.MagicFood);
		MainClass.RamoraCooked = new RamoraCookedClass(999999999, 1.0E9f, false).setUnlocalizedName("RamoraCooked").setCreativeTab(MainClass.MagicFood);
		MainClass.SwordofGryffindor = new SwordofGryffindorClass(MainClass.MagicWeaponMaterial).setFull3D().setUnlocalizedName("SwordofGryffindor").setCreativeTab(MainClass.MagicItems);
		MainClass.Trident = new TridentClass(MainClass.TridentMaterial).setUnlocalizedName("Trident").setUnlocalizedName("Trident").setCreativeTab(MainClass.MagicItems);
		MainClass.AurorLegs = new AurorArmorClass(MainClass.AurorArmor, MainClass.AurorLegsID, 2).setUnlocalizedName("AurorLegs").setCreativeTab(MainClass.MagicItems);
		MainClass.AurorChest = new AurorArmorClass(MainClass.AurorArmor, MainClass.AurorChestID, 1).setUnlocalizedName("AurorChest").setCreativeTab(MainClass.MagicItems);
		MainClass.AurorHat = new AurorArmorClass(MainClass.AurorArmor, MainClass.AurorHatID, 0).setUnlocalizedName("AurorHat").setCreativeTab(MainClass.MagicItems);
		MainClass.AurorShoes = new AurorArmorClass(MainClass.AurorArmor, MainClass.AurorShoesID, 3).setUnlocalizedName("AurorShoes").setCreativeTab(MainClass.MagicItems);
		MainClass.DeathEaterLegs = new DeathEaterArmorClass(MainClass.DeathEaterArmor, MainClass.DeathEaterLegsID, 2).setUnlocalizedName("DeathEaterLegs").setCreativeTab(MainClass.MagicItems);
		MainClass.DeathEaterChest = new DeathEaterArmorClass(MainClass.DeathEaterArmor, MainClass.DeathEaterChestID, 1).setUnlocalizedName("DeathEaterChest").setCreativeTab(MainClass.MagicItems);
		MainClass.DeathEaterHat = new DeathEaterArmorClass(MainClass.DeathEaterArmor, MainClass.DeathEaterHatID, 0).setUnlocalizedName("DeathEaterHat").setCreativeTab(MainClass.MagicItems);
		MainClass.DeathEaterShoes = new DeathEaterArmorClass(MainClass.DeathEaterArmor, MainClass.DeathEaterShoesID, 3).setUnlocalizedName("DeathEaterShoes").setCreativeTab(MainClass.MagicItems);
		MainClass.WerewolfLegs = new WerewolfArmorClass(MainClass.WerewolfFur, MainClass.WerewolfLegsID, 2).setUnlocalizedName("WerewolfLegs").setCreativeTab(MainClass.MagicItems);
		MainClass.WerewolfChest = new WerewolfArmorClass(MainClass.WerewolfFur, MainClass.WerewolfChestID, 1).setUnlocalizedName("WerewolfChest").setCreativeTab(MainClass.MagicItems);
		MainClass.WerewolfHead = new WerewolfArmorClass(MainClass.WerewolfFur, MainClass.WerewolfHeadID, 0).setUnlocalizedName("WerewolfHead").setCreativeTab(MainClass.MagicItems);
		MainClass.WerewolfFeet = new WerewolfArmorClass(MainClass.WerewolfFur, MainClass.WerewolfFeetID, 3).setUnlocalizedName("WerewolfFeet").setCreativeTab(MainClass.MagicItems);

		this.eventWorldGen = new WizardWorldGen();

		GameRegistry.registerItem(MainClass.AurorLegs, "AurorLegs");
		GameRegistry.registerItem(MainClass.AurorChest, "AurorChest");
		GameRegistry.registerItem(MainClass.AurorHat, "AurorHat");
		GameRegistry.registerItem(MainClass.AurorShoes, "AurorShoes");
		GameRegistry.registerItem(MainClass.DeathEaterLegs, "DeathEaterLegs");
		GameRegistry.registerItem(MainClass.DeathEaterChest, "DeathEaterChest");
		GameRegistry.registerItem(MainClass.DeathEaterHat, "DeathEaterHat");
		GameRegistry.registerItem(MainClass.DeathEaterShoes, "DeathEaterShoes");

		GameRegistry.registerWorldGenerator(this.eventWorldGen, 6);

		EntityRegistry.registerGlobalEntityID(EntityQuaffle.class, "Quaffle", EntityRegistry.findGlobalUniqueEntityId());

		MainClass.proxy.registerItemRenderers();
		MainClass.proxy.preInit();
		MainClass.proxy.renderStuff();
		MainClass.proxy.registerItemRenderers();
		EntityHandler.registerHorntail(EntityHorntail.class, "Horntail");
		EntityHandler.registerHorntail(EntityUkaranianIronbelly.class, "UkaranianIronbelly");
		MagicLeveling.calculateNeededExp();
		EntityHandler.registerBasilisk(EntityBasilisk.class, "Basilisk");
		EntityHandler.registerFluffy(EntityFluffy.class, "Fluffy");
		EntityHandler.registerWerewolf(EntityWerewolfMob.class, "Werewolf");
		EntityHandler.registerHippogriff(EntityHippogriff.class, "Hippogriff");
		EntityHandler.registerPhoenix(EntityPhoenix.class, "Phoenix");
		EntityHandler.registerDementor(EntityDementor.class, "Dementor");
		EntityHandler.registerBook(EntityBook.class, "Book");
		EntityHandler.registerSnake(EntitySnake.class, "Snake");
		EntityHandler.registerShield(EntityShield.class, "Shield");
		EntityHandler.registerPatronus(EntityPatronus.class, "Patronus");
		EntityHandler.registerBird(EntityBird.class, "Bird");
		EntityHandler.registerImperio(EntityImperioMob.class, "Imperio");
		EntityHandler.registerMonsterBook(EntityMonsterBook.class, "MonsterBook");
		EntityHandler.registerLevitate(EntityLevitate.class, "Levitate");
		EntityHandler.registerSnitch(EntityGoldenSnitch.class, "GoldenSnitch");
		EntityHandler.registerBludger(EntityBludger.class, "Bludger");
		EntityHandler.registerFord(EntityFordAnglia.class, "FordAnglia");
		EntityHandler.registerMotocycle(EntityMotorbike.class, "Motorbike");
		EntityHandler.registerMotocycle2(EntityMotorbike2.class, "Motorbike2");
		EntityHandler.registerBroom(EntityFlyingBroomstick.class, "FlyingBroomstick");
		EntityHandler.registerSpider(EntityAragog.class, "Aragog");
		EntityHandler.registerForm(EntityWerewolf.class, "WerewolfForm");
		EntityHandler.registerForm(EntityStagForm.class, "StagForm");
		EntityHandler.registerForm(EntityDogForm.class, "DogForm");
		EntityHandler.registerForm(EntityCatForm.class, "CatForm");
		EntityHandler.registerForm(EntityRatForm.class, "RatForm");
		EntityHandler.registerForm(EntityPhoenixForm.class, "PhoenixForm");
		EntityHandler.registerForm(EntityRavenForm.class, "RavenForm");
		EntityHandler.registerForm(EntitySnidgetForm.class, "SnidgetForm");
		EntityHandler.registerForm(EntityFalconForm.class, "FalconForm");
		EntityHandler.registerForm(EntityOwlForm.class, "OwlForm");
		EntityHandler.registerProjectile(ExpelliarmusProjectile.class, "ExpelliarmusProjectile");
		EntityHandler.registerProjectile(AvadakedavraProjectile.class, "AvadakedavraProjectile");
		EntityHandler.registerProjectile(PatronusProjectile.class, "PatronusProjectile");
		EntityHandler.registerNagini(EntityNagini.class, "Nagini");
		EntityHandler.registerSnitch(EntityKey.class, "Key");
		EntityHandler.registerSnitch(EntityMasterKey.class, "MasterKey");
		EntityHandler.registerGhost(EntityGhost.class, "Ghost");
		EntityHandler.registerFiendfyre(EntityFiendfyreDragon.class, "FiendfyreDragon");
		EntityHandler.registerProjectile(StupefyProjectile.class, "StupefyProjectile");
		EntityHandler.registerProjectile(ConfringoProjectile.class, "ConfringoProjectile");
		EntityHandler.registerProjectile(ReductoProjectile.class, "ReductoProjectile");
		EntityHandler.registerProjectile(CrucioProjectile.class, "CrucioProjectile");
		EntityHandler.registerProjectile(ImperioProjectile.class, "ImperioProjectile");
		EntityHandler.registerProjectile(AraniaExumaiProjectile.class, "AraniaExumaiProjectile");
		EntityHandler.registerProjectile(SectumsempraProjectile.class, "SectumsempraProjectile");
		EntityHandler.registerProjectile(LevicorpusProjectile.class, "LevicorpusProjectile");
		EntityHandler.registerProjectile(IncendioProjectile.class, "IncendioProjectile");
		EntityHandler.registerProjectile(StunProjectile.class, "StunProjectile");
		EntityHandler.registerProjectile(ConfundoProjectile.class, "ConfundoProjectile");
		EntityHandler.registerCabinet(EntityCabinet.class, "EntityCabinet");
		EntityHandler.registerCabinet(EntityCabinet2.class, "EntityCabinet2");
		EntityHandler.registerElf(EntityHouseElf.class, "EntityHouseElf");
		EntityHandler.registerBoggart(EntityBoggartDementor.class, "BoggartDementor");
		EntityHandler.registerProjectile(PatronusStrongProjectile.class, "PatronusStrongProjectile");
		EntityHandler.registerProjectile(ExpelliarmusStrongProjectile.class, "ExpelliarmusStrongProjectile");
		EntityHandler.registerProjectile(ConfringoStrongProjectile.class, "ConfringoStrongProjectile");
		EntityHandler.registerProjectile(ReductoStrongProjectile.class, "ReductoStrongProjectile");
		EntityHandler.registerProjectile(CrucioStrongProjectile.class, "CrucioStrongProjectile");
		EntityHandler.registerProjectile(LevicorpusStrongProjectile.class, "LevicorpusStrongProjectile");
		EntityHandler.registerProjectile(StunStrongProjectile.class, "StunStrongProjectile");
		EntityHandler.registerProjectile(ConfundoStrongProjectile.class, "ConfundStrongoProjectile");
		EntityHandler.registerProjectile(StupefyStrongProjectile.class, "StupefyStrongProjectile");
		EntityHandler.registerWingedHorse(EntityWingedHorse.class, "WingedHorse");
		EntityHandler.registerProjectile(SectumsempraStrongProjectile.class, "SectumsempraStrongProjectile");
		EntityHandler.registerUnicorn(EntityUnicorn.class, "Unicorn");
		EntityHandler.registerThestral(EntityThestral.class, "Thestral");
		EntityHandler.registerBillywig(EntityBillywig.class, "Billywig");
		EntityHandler.registerGriffin(EntityGriffin.class, "Griffin");
		EntityHandler.registerGrindylow(EntityGrindylow.class, "Grindylow");
		EntityHandler.registerHippocampus(EntityHippocampus.class, "Hippocampus");
		EntityHandler.registerPuffskein(EntityPuffskein.class, "Puffskein");
		EntityHandler.registerNogtail(EntityNogtail.class, "Nogtail");
		EntityHandler.registerRunespoor(EntityRunespoor.class, "Runespoor");
		EntityHandler.registerTroll(EntityTroll.class, "Troll");
		EntityHandler.registerRedCap(EntityRedCap.class, "RedCap");
		EntityHandler.registerBowtruckle(EntityBowtruckle.class, "Bowtruckle");
		EntityHandler.registerPixie(EntityPixie.class, "Pixie");
		EntityHandler.registerGoblin(EntityGoblin.class, "Goblin");
		EntityHandler.registerFairy(EntityFairy.class, "Fairy");
		EntityHandler.registerAugurey(EntityAugurey.class, "Augurey");
		EntityHandler.registerClabbert(EntityClabbert.class, "Clabbert");
		EntityHandler.registerBundimun(EntityBundimun.class, "Bundimun");
		EntityHandler.registerChizpurfle(EntityChizpurfle.class, "Chizpurfle");
		EntityHandler.registerMermaid(EntityMermaid.class, "Mermaid");
		EntityHandler.registerCentaur(EntityCentaur.class, "Centaur");
		EntityHandler.registerDugbog(EntityDugbog.class, "Dugbog");
		EntityHandler.registerGnome(EntityGnome.class, "Gnome");
		EntityHandler.registerTebo(EntityTebo.class, "Tebo");
		EntityHandler.registerRamora(EntityRamora.class, "Ramora");
		EntityHandler.registerMoke(EntityMoke.class, "Moke");
		EntityHandler.registerJobberknoll(EntityJobberknoll.class, "Jobberknoll");
		EntityHandler.registerSnidget(EntitySnidget.class, "Snidget");
		EntityHandler.registerDemiguise(EntityDemiguise.class, "Demiguise");
		EntityHandler.registerFireCrab(EntityFireCrab.class, "FireCrab");
		EntityHandler.registerFlobberworm(EntityFlobberworm.class, "Flobberworm");
		EntityHandler.registerFwooper(EntityFwooper.class, "Fwooper");
		EntityHandler.registerGhoul(EntityGhoul.class, "Ghoul");
		EntityHandler.registerGraphorn(EntityGraphorn.class, "Graphorn");
		EntityHandler.registerHorklump(EntityHorklump.class, "Horklump");
		EntityHandler.registerImp(EntityImp.class, "Imp");
		EntityHandler.registerJarvey(EntityJarvey.class, "Jarvey");
		EntityHandler.registerKelpie(EntityKelpie.class, "Kelpie");
		EntityHandler.registerKnarl(EntityKnarl.class, "Knarl");
		EntityHandler.registerKneazle(EntityKneazle.class, "Kneazle");
		EntityHandler.registerNundu(EntityNundu.class, "Nundu");
		EntityHandler.registerOccamy(EntityOccamy.class, "Occamy");
		EntityHandler.registerQuintaped(EntityQuintaped.class, "Quintaped");
		EntityHandler.registerReem(EntityReem.class, "Reem");
		EntityHandler.registerVeela(EntityVeela.class, "Veela");
		EntityHandler.registerLeprechaun(EntityLeprechaun.class, "Leprechaun");
		EntityHandler.registerStoneSoldier(EntityStoneSoldier.class, "StoneSoldier");

		GameRegistry.registerTileEntity(TileEntityWandCrafter.class, "TileEntityWandCrafter");
		GameRegistry.registerTileEntity(TileEntityStoneSoldierBlock.class, "TileEntityStoneSoldierBlock");
		GameRegistry.registerTileEntity(TileEntityPensieve.class, "TileEntityPensieve");
		GameRegistry.registerTileEntity(TileEntityBoggartChestLocked.class, "TileEntityBoggartChestLocked");
		GameRegistry.registerTileEntity(TileEntityBoggartChestOpen.class, "TileEntityBoggartChestOpen");
		GameRegistry.registerTileEntity(TileEntityTriCup.class, "TileEntityTriCup");
		GameRegistry.registerTileEntity(TileEntityEveryFlavourBeans.class, "TileEntityEveryFlavourBeans");
		GameRegistry.registerTileEntity(TileEntityHand.class, "TileEntityHand");
		GameRegistry.registerTileEntity(TileEntityGoldenEggOpen.class, "TileEntityGoldenEggOpen");
		GameRegistry.registerTileEntity(TileEntityGoldenEgg.class, "TileEntityGoldenEgg");
		GameRegistry.registerTileEntity(TileEntityDarkMarkClass.class, "TileEntityDarkMarkClass");
		GameRegistry.registerTileEntity(TileEntityLocket.class, "TileEntityLocket");
		GameRegistry.registerTileEntity(TileEntityPensievePlane.class, "TileEntityPensievePlane");
		GameRegistry.registerTileEntity(TileEntityHat.class, "TileEntityHat");
		GameRegistry.registerTileEntity(TileEntityCup.class, "TileEntityCup");
		GameRegistry.registerTileEntity(TileEntityDiadem.class, "TileEntityDiadem");
		GameRegistry.registerTileEntity(TileEntityDiary.class, "TileEntityDiary");
		GameRegistry.registerTileEntity(TileEntityRing.class, "TileEntityRing");
		GameRegistry.registerTileEntity(TileEntityCabinet.class, "TileEntityCabinet");
		GameRegistry.registerTileEntity(TileEntityCrystalball.class, "TileEntityCrystalball");
		GameRegistry.registerTileEntity(TileEntityMirror.class, "TileEntityMirror");
		GameRegistry.registerTileEntity(TileEntityGOF.class, "TileEntityGOF");

	}

	@Mod.EventHandler
	@SideOnly(Side.CLIENT)
	public void postInit(final FMLPostInitializationEvent event) {
		MinecraftForge.EVENT_BUS.register(new SpellGUI(Minecraft.getMinecraft()));
	}

	@Mod.EventHandler
	public void load(final FMLInitializationEvent event) {
		MinecraftForge.EVENT_BUS.register(new MagicEventHandler());
		NetworkRegistry.INSTANCE.registerGuiHandler(this, new GuiHandler());
	}

	public static boolean isServer() {
		return FMLCommonHandler.instance().getEffectiveSide() == Side.SERVER;
	}

}
