package snidgert.harrypottermod.mobs;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class WerewolfArmor extends ModelBiped {

	ModelRenderer head;
	ModelRenderer body;
	ModelRenderer rightarm;
	ModelRenderer leftarm;
	ModelRenderer rightleg;
	ModelRenderer leftleg;
	ModelRenderer rightshoulder;
	ModelRenderer leftshoulder;
	ModelRenderer rightfinger1;
	ModelRenderer rightfinger2;
	ModelRenderer rightfinger3;
	ModelRenderer leftfinger1;
	ModelRenderer leftfinger2;
	ModelRenderer leftfinger3;
	ModelRenderer righttoe1;
	ModelRenderer righttoe2;
	ModelRenderer righttoe3;
	ModelRenderer lefttoe1;
	ModelRenderer lefttoe2;
	ModelRenderer lefttoe3;
	ModelRenderer mouth;
	ModelRenderer leftear;
	ModelRenderer leftupperear;
	ModelRenderer rightear;
	ModelRenderer rightupperear;
	ModelRenderer tail;
	ModelRenderer tail2;

	public WerewolfArmor(final float scale) {
		super(scale, 0.0f, 128, 128);
		((ModelBase) this).textureWidth = 128;
		((ModelBase) this).textureHeight = 128;
		(this.head = new ModelRenderer(this, 88, 29)).addBox(-4.0f, -8.0f, -4.0f, 8, 8, 8);
		this.head.setTextureSize(64, 32);
		this.head.mirror = true;
		this.setRotation(this.head, 0.0f, 0.0f, 0.0f);
		(this.body = new ModelRenderer(this, 37, 53)).addBox(-4.0f, 0.0f, -2.0f, 8, 12, 4);
		this.body.setTextureSize(64, 32);
		this.body.mirror = true;
		this.setRotation(this.body, 0.0f, 0.0f, 0.0f);
		(this.rightarm = new ModelRenderer(this, 4, 62)).addBox(-3.5f, -2.0f, -2.0f, 4, 12, 4);
		this.rightarm.setTextureSize(64, 32);
		this.rightarm.mirror = true;
		this.setRotation(this.rightarm, 0.0f, 0.0f, 0.0f);
		(this.leftarm = new ModelRenderer(this, 75, 63)).addBox(-0.5f, -2.0f, -2.0f, 4, 12, 4);
		this.leftarm.setTextureSize(64, 32);
		this.leftarm.mirror = true;
		this.setRotation(this.leftarm, 0.0f, 0.0f, 0.0f);
		(this.rightleg = new ModelRenderer(this, 30, 90)).addBox(-2.0f, 0.0f, -2.0f, 4, 12, 4);
		this.rightleg.setTextureSize(64, 32);
		this.rightleg.mirror = true;
		this.setRotation(this.rightleg, 0.0f, 0.0f, 0.0f);
		(this.leftleg = new ModelRenderer(this, 60, 90)).addBox(-2.0f, 0.0f, -2.0f, 4, 12, 4);
		this.leftleg.setTextureSize(64, 32);
		this.leftleg.mirror = true;
		this.setRotation(this.leftleg, 0.0f, 0.0f, 0.0f);
		(this.rightshoulder = new ModelRenderer(this, 0, 49)).addBox(-4.0f, -2.5f, -2.5f, 5, 5, 5);
		this.rightshoulder.setTextureSize(64, 32);
		this.rightshoulder.mirror = true;
		this.setRotation(this.rightshoulder, 0.0f, 0.0f, 0.0f);
		(this.leftshoulder = new ModelRenderer(this, 75, 50)).addBox(-1.0f, -2.5f, -2.5f, 5, 5, 5);
		this.leftshoulder.setTextureSize(64, 32);
		this.leftshoulder.mirror = true;
		this.setRotation(this.leftshoulder, 0.0f, 0.0f, 0.0f);
		(this.rightfinger1 = new ModelRenderer(this, 15, 90)).addBox(-3.5f, 10.0f, -2.0f, 1, 1, 1);
		this.rightfinger1.setTextureSize(64, 32);
		this.rightfinger1.mirror = true;
		this.setRotation(this.rightfinger1, 0.0f, 0.0f, 0.0f);
		(this.rightfinger2 = new ModelRenderer(this, 0, 90)).addBox(-3.5f, 10.0f, 1.0f, 1, 1, 1);
		this.rightfinger2.setTextureSize(64, 32);
		this.rightfinger2.mirror = true;
		this.setRotation(this.rightfinger2, 0.0f, 0.0f, 0.0f);
		(this.rightfinger3 = new ModelRenderer(this, 7, 90)).addBox(-3.5f, 10.0f, -0.5f, 1, 1, 1);
		this.rightfinger3.setTextureSize(64, 32);
		this.rightfinger3.mirror = true;
		this.setRotation(this.rightfinger3, 0.0f, 0.0f, 0.0f);
		(this.leftfinger1 = new ModelRenderer(this, 75, 85)).addBox(2.5f, 10.0f, -2.0f, 1, 1, 1);
		this.leftfinger1.setTextureSize(64, 32);
		this.leftfinger1.mirror = true;
		this.setRotation(this.leftfinger1, 0.0f, 0.0f, 0.0f);
		(this.leftfinger2 = new ModelRenderer(this, 95, 85)).addBox(2.5f, 10.0f, 1.0f, 1, 1, 1);
		this.leftfinger2.setTextureSize(64, 32);
		this.leftfinger2.mirror = true;
		this.setRotation(this.leftfinger2, 0.0f, 0.0f, 0.0f);
		(this.leftfinger3 = new ModelRenderer(this, 85, 85)).addBox(2.5f, 10.0f, -0.5f, 1, 1, 1);
		this.leftfinger3.setTextureSize(64, 32);
		this.leftfinger3.mirror = true;
		this.setRotation(this.leftfinger3, 0.0f, 0.0f, 0.0f);
		(this.righttoe1 = new ModelRenderer(this, 20, 115)).addBox(-2.0f, 11.0f, -3.0f, 1, 1, 1);
		this.righttoe1.setTextureSize(64, 32);
		this.righttoe1.mirror = true;
		this.setRotation(this.righttoe1, 0.0f, 0.0f, 0.0f);
		(this.righttoe2 = new ModelRenderer(this, 36, 115)).addBox(1.0f, 11.0f, -3.0f, 1, 1, 1);
		this.righttoe2.setTextureSize(64, 32);
		this.righttoe2.mirror = true;
		this.setRotation(this.righttoe2, 0.0f, 0.0f, 0.0f);
		(this.righttoe3 = new ModelRenderer(this, 28, 115)).addBox(-0.5f, 11.0f, -3.0f, 1, 1, 1);
		this.righttoe3.setTextureSize(64, 32);
		this.righttoe3.mirror = true;
		this.setRotation(this.righttoe3, 0.0f, 0.0f, 0.0f);
		(this.lefttoe1 = new ModelRenderer(this, 57, 115)).addBox(-2.0f, 11.0f, -3.0f, 1, 1, 1);
		this.lefttoe1.setTextureSize(64, 32);
		this.lefttoe1.mirror = true;
		this.setRotation(this.lefttoe1, 0.0f, 0.0f, 0.0f);
		(this.lefttoe2 = new ModelRenderer(this, 72, 115)).addBox(1.0f, 11.0f, -3.0f, 1, 1, 1);
		this.lefttoe2.setTextureSize(64, 32);
		this.lefttoe2.mirror = true;
		this.setRotation(this.lefttoe2, 0.0f, 0.0f, 0.0f);
		(this.lefttoe3 = new ModelRenderer(this, 64, 115)).addBox(-0.5f, 11.0f, -3.0f, 1, 1, 1);
		this.lefttoe3.setTextureSize(64, 32);
		this.lefttoe3.mirror = true;
		this.setRotation(this.lefttoe3, 0.0f, 0.0f, 0.0f);
		(this.mouth = new ModelRenderer(this, 91, 15)).addBox(-2.0f, -5.0f, -9.0f, 4, 4, 5);
		this.mouth.setTextureSize(64, 32);
		this.mouth.mirror = true;
		this.setRotation(this.mouth, 0.0f, 0.0f, 0.0f);
		(this.leftear = new ModelRenderer(this, 82, 24)).addBox(-4.0f, -9.0f, 1.0f, 1, 1, 2);
		this.leftear.setTextureSize(64, 32);
		this.leftear.mirror = true;
		this.setRotation(this.leftear, 0.0f, 0.0f, 0.0f);
		(this.leftupperear = new ModelRenderer(this, 82, 19)).addBox(-4.0f, -10.0f, 1.5f, 1, 1, 1);
		this.leftupperear.setTextureSize(64, 32);
		this.leftupperear.mirror = true;
		this.setRotation(this.leftupperear, 0.0f, 0.0f, 0.0f);
		(this.rightear = new ModelRenderer(this, 112, 22)).addBox(3.0f, -9.0f, 1.0f, 1, 1, 2);
		this.rightear.setTextureSize(64, 32);
		this.rightear.mirror = true;
		this.setRotation(this.rightear, 0.0f, 0.0f, 0.0f);
		(this.rightupperear = new ModelRenderer(this, 113, 17)).addBox(3.0f, -10.0f, 1.5f, 1, 1, 1);
		this.rightupperear.setTextureSize(64, 32);
		this.rightupperear.mirror = true;
		this.setRotation(this.rightupperear, 0.0f, 0.0f, 0.0f);
		(this.tail = new ModelRenderer(this, 37, 72)).addBox(-1.5f, 10.0f, 2.0f, 3, 3, 7);
		this.tail.setTextureSize(64, 32);
		this.tail.mirror = true;
		this.setRotation(this.tail, -0.1308997f, 0.0f, 0.0f);
		(this.tail2 = new ModelRenderer(this, 102, 53)).addBox(-2.0f, 8.5f, 9.0f, 4, 4, 6);
		this.tail2.mirror = true;
		this.setRotation(this.tail2, -0.2617994f, 0.0f, 0.0f);
		super.bipedHead.addChild(this.head);
		super.bipedBody.addChild(this.body);
		super.bipedRightArm.addChild(this.rightarm);
		super.bipedLeftArm.addChild(this.leftarm);
		super.bipedRightLeg.addChild(this.rightleg);
		super.bipedLeftLeg.addChild(this.leftleg);
		super.bipedRightArm.addChild(this.rightshoulder);
		super.bipedLeftArm.addChild(this.leftshoulder);
		super.bipedRightArm.addChild(this.rightfinger1);
		super.bipedRightArm.addChild(this.rightfinger2);
		super.bipedRightArm.addChild(this.rightfinger3);
		super.bipedLeftArm.addChild(this.leftfinger1);
		super.bipedLeftArm.addChild(this.leftfinger2);
		super.bipedLeftArm.addChild(this.leftfinger3);
		super.bipedRightLeg.addChild(this.righttoe1);
		super.bipedRightLeg.addChild(this.righttoe2);
		super.bipedRightLeg.addChild(this.righttoe3);
		super.bipedLeftLeg.addChild(this.lefttoe1);
		super.bipedLeftLeg.addChild(this.lefttoe2);
		super.bipedLeftLeg.addChild(this.lefttoe3);
		super.bipedHead.addChild(this.mouth);
		super.bipedHead.addChild(this.leftear);
		super.bipedHead.addChild(this.leftupperear);
		super.bipedHead.addChild(this.rightear);
		super.bipedHead.addChild(this.rightupperear);
		super.bipedBody.addChild(this.tail);
		super.bipedBody.addChild(this.tail2);
	}

	@Override
	public void render(final Entity entity, final float f, final float f1, final float f2, final float f3, final float f4, final float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

	private void setRotation(final ModelRenderer model, final float x, final float y, final float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
